@testset "Misc" begin
  include("Misc/Integer.jl")
  include("Misc/psibound.jl")
  include("Misc/FiniteField.jl")
  include("Misc/Primes.jl")
  include("Misc/meataxe.jl")
  include("Misc/stable_subgroups.jl")
  include("Misc/NumberField.jl")
  include("Misc/Poly.jl")
  include("Misc/OrdLocalization.jl")
  include("Misc/jordan_test.jl")
  include("Misc/RelFinField.jl")
  include("Misc/UnitsModM.jl")
  include("Misc/Matrix.jl")
  include("Misc/PIDIdeal.jl")
  include("Misc/MSet.jl")
  include("Misc/AVLTrees.jl")
end
