@testset "Orders in absolute number fields" begin
  include("AbsNumFieldOrder{AbsSimpleNumField, AbsSimpleNumFieldElem}/AbsNumFieldOrder{AbsSimpleNumField, AbsSimpleNumFieldElem}.jl")
  include("AbsNumFieldOrder{AbsSimpleNumField, AbsSimpleNumFieldElem}/Elem.jl")
  include("AbsNumFieldOrder{AbsSimpleNumField, AbsSimpleNumFieldElem}/TorsionUnits.jl")
  include("AbsNumFieldOrder{AbsSimpleNumField, AbsSimpleNumFieldElem}/Ideal.jl")
  include("AbsNumFieldOrder{AbsSimpleNumField, AbsSimpleNumFieldElem}/FracIdl.jl")
  include("AbsNumFieldOrder{AbsSimpleNumField, AbsSimpleNumFieldElem}/ResidueRing.jl")
  include("AbsNumFieldOrder{AbsSimpleNumField, AbsSimpleNumFieldElem}/ResidueField.jl")
  include("AbsNumFieldOrder{AbsSimpleNumField, AbsSimpleNumFieldElem}/Clgp.jl")
  include("AbsNumFieldOrder{AbsSimpleNumField, AbsSimpleNumFieldElem}/RayClassGroup.jl")
  include("AbsNumFieldOrder{AbsSimpleNumField, AbsSimpleNumFieldElem}/ResidueRingMultGrp.jl")
  include("AbsNumFieldOrder{AbsSimpleNumField, AbsSimpleNumFieldElem}/Overorders.jl")
  include("AbsNumFieldOrder{AbsSimpleNumField, AbsSimpleNumFieldElem}/LinearAlgebra.jl")
  include("AbsNumFieldOrder{AbsSimpleNumField, AbsSimpleNumFieldElem}/PicardGroup.jl")
  include("AbsNumFieldOrder{AbsSimpleNumField, AbsSimpleNumFieldElem}/NarrowPicardGroup.jl")
end
