@testset "Orders in absolute number fields" begin
  include("NfOrd/NfOrd.jl")
  include("NfOrd/Elem.jl")
  include("NfOrd/TorsionUnits.jl")
  include("NfOrd/Ideal.jl")
  include("NfOrd/FracIdl.jl")
  include("NfOrd/ResidueRing.jl")
  include("NfOrd/ResidueField.jl")
  include("NfOrd/Clgp.jl")
  include("NfOrd/RayClassGroup.jl")
  include("NfOrd/ResidueRingMultGrp.jl")
  include("NfOrd/Overorders.jl")
  include("NfOrd/LinearAlgebra.jl")
  include("NfOrd/PicardGroup.jl")
  include("NfOrd/NarrowPicardGroup.jl")
end
