@testset "Quadratic and hermitian forms" begin
  include("QuadForm/Basic.jl")
  include("QuadForm/Lattices.jl")
  include("QuadForm/Genus.jl")
  include("QuadForm/Morphism.jl")
  include("QuadForm/Enumeration.jl")
  include("QuadForm/MassQuad.jl")
  include("QuadForm/MassHerm.jl")
  include("QuadForm/Quad.jl")
  include("QuadForm/QuadBin.jl")
  include("QuadForm/Herm.jl")
  include("QuadForm/Torsion.jl")
  include("QuadForm/Quad/PadicLift.jl")
  include("QuadForm/ClosestVector.jl")
  include("QuadForm/IO.jl")
end
