function _zero_module_like(M::EmbeddedModule{_PID})
  B = zero_matrix(overring(M), 0, ambient_rank(M))
  return embedded_module(ring(M), overring(M), B;
                         overstructure = overstructure(M), is_basis_matrix = true)
end

function _zero_module_like(M::EmbeddedModule{_DD})
  B = zero_matrix(overring(M), 0, ambient_rank(M))
  C = typeof(fractional_ideal(ring(M), one(ring(M))))[]
  P = Hecke.pseudo_matrix(ring(M), B, C)
  return embedded_module(ring(M), overring(M), P;
                         overstructure = overstructure(M), is_basis_matrix = true)
end

function _sum(M::EmbeddedModule, N::EmbeddedModule, ::Type{_PID})
  B = vcat(basis_matrix(M), basis_matrix(N))
  return embedded_module(ring(M), overring(M), B; overstructure = overstructure(M))
end

function _sum(M::EmbeddedModule, N::EmbeddedModule, ::Type{_DD})
  P = vcat(basis_matrix(M), basis_matrix(N))
  return embedded_module(ring(M), overring(M), P; overstructure = overstructure(M))
end

function +(M::EmbeddedModule, N::EmbeddedModule)
  _check_compatible(M, N)
  return _sum(M, N, _ring_type(M))
end

function _intersect(M::EmbeddedModule, N::EmbeddedModule, ::Type{_PID})
  if iszero(rank(M)) || iszero(rank(N))
    return _zero_module_like(M)
  end

  BM = basis_matrix(M)
  BN = basis_matrix(N)
  # Integral relations (u, v) with u*BM = v*BN parametrize M intersect N.
  C, _ = decompose(fraction_map(M), vcat(BM, -BN))
  relations = kernel(C; side = :left)
  if iszero(nrows(relations))
    return _zero_module_like(M)
  end

  KM = sub(relations, 1:nrows(relations), 1:nrows(BM))
  B = change_base_ring(overring(M), KM)*BM
  return embedded_module(ring(M), overring(M), B; overstructure = overstructure(M))
end

function _intersect(M::EmbeddedModule, N::EmbeddedModule, ::Type{_DD})
  if iszero(rank(M)) || iszero(rank(N))
    return _zero_module_like(M)
  end

  PM = deepcopy(basis_matrix(M))
  PN = deepcopy(basis_matrix(N))
  if nrows(PN) > nrows(PM)
    PM, PN = PN, PM
  end

  # In the module generated by (x, x), x in M, and (y, 0), y in N,
  # the rows whose first component vanishes project onto M intersect N.
  P1 = hcat(PM, deepcopy(PM))
  Z = Hecke.pseudo_matrix(ring(M),
                    zero_matrix(overring(M), nrows(PN), ncols(PN)),
                    deepcopy(Hecke.coefficient_ideals(PN)))
  P2 = hcat(PN, Z)
  H = Hecke.pseudo_hnf(vcat(P1, P2), :upperright)
  r = nrows(PM)
  n = ncols(PM)
  P = sub(H, r + 1:r + nrows(PN), n + 1:2*n)
  return embedded_module(ring(M), overring(M), P; overstructure = overstructure(M))
end

function intersect(M::EmbeddedModule, N::EmbeddedModule)
  _check_compatible(M, N)
  return _intersect(M, N, _ring_type(M))
end
