################################################################################
#
#  Constructors
#
################################################################################

ideal(O::GenOrd, a::RingElement, b::RingElement) = GenOrdIdl(O, a, b)
ideal(O::GenOrd, a::RingElement) = GenOrdIdl(O, a)

function ideal(O::GenOrd, M::MatElem; M_in_hnf::Bool = false)
  n = degree(O)
  @req base_ring(M) === coefficient_ring(O) "matrix must be over the coefficient ring of O"
  @req ncols(M) == n "matrix must have exactly degree(O) = $n columns"
  @req nrows(M) >= n "matrix must have at least degree(O) = $n rows"

  H = M_in_hnf ? M : hnf(M, :lowerleft)
  @hassert :GenOrd 1 !M_in_hnf || H == hnf(H, :lowerleft)

  # the canonical lower-left HNF basis lives in the bottom n rows
  # also ensure that we materialize a view
  if nrows(H) > n || H isa AbstractAlgebra.Generic.MatSpaceView
    H = sub(H, nrows(H) - n + 1:nrows(H), 1:n)
  end

  return GenOrdIdl(O, H)
end

function AbstractAlgebra.zero(a::GenOrdIdl)
  O = a.order
  return GenOrdIdl(O, O(0))
end

# TODO: fix me
AbstractAlgebra.iszero(I::GenOrdIdl) = (I.is_zero == 1)

has_2_elem(A::GenOrdIdl) = isdefined(A, :gen_two)

@doc raw"""
    isone(A::GenOrdIdl) -> Bool
    is_unit(A::GenOrdIdl) -> Bool

Tests if $A$ is the trivial ideal generated by $1$.
"""
function isone(I::GenOrdIdl)
  if isdefined(I, :norm)
    return isone(norm(I; copy = false))
  end
  return isone(minimum(I; copy = false))
end


################################################################################
#
#  Basic field access
#
################################################################################

@doc raw"""
    order(x::GenOrdIdl) -> GenOrd

Return the order, of which $x$ is an ideal.
"""
Hecke.order(a::GenOrdIdl) = a.order

################################################################################
#
#  Copy
#
################################################################################

function Base.deepcopy_internal(I::GenOrdIdl{S, T}, dict::IdDict) where {S, T}
  J = GenOrdIdl(order(I))
  for f in fieldnames(typeof(I))
    f === :order && continue
    if isdefined(I, f)
      setfield!(J, f, Base.deepcopy_internal(getfield(I, f), dict))
    end
  end
  return J
end

################################################################################
#
#  Hash
#
################################################################################

function Base.hash(I::GenOrdIdl, h::UInt)
  b = 0x11ba13ff011affd1%UInt
  return xor(b, hash(basis_matrix(I; copy = false), h))
end

################################################################################
#
#  IO
#
################################################################################

function show(io::IO, id::GenOrdIdl)
  print(io, "Ideal of ", id.order)
  if has_2_elem(id)
    print(io, "\nGenerators: <", id.gen_one, ", ", id.gen_two, ">" )
  else
    print(io, "\nGenerators: <no 2-elts present>");
  end
  if has_norm(id)
    print(io, "\nNorm: ", id.norm);
  end
  if has_minimum(id)
    print(io, "\nMinimum: ", id.minimum);
  end
  if isdefined(id, :princ_gen)
    print(io, "\nPrincipal generator ", id.princ_gen)
  end
  if isdefined(id, :basis_matrix)
    print(io, "\nBasis_matrix \n", id.basis_matrix)
  end
end

###########################################################################################
#
#   HNF
#
###########################################################################################

# Ideals are row modules
# They are represented by n x n matrix (with n equal to the order degree)
#   with basis vectors forming matrix rows.
# The shape of this matrix is lower-left HNF.
# Zero ideals are treated explicitly, they are the only exception to full-column rank rule
# For all HNF functions we assume full column rank

# HNF of M assuming g is a multiple of the largest elementary divisor of the
#   row module L of M, that is g*R^m \subseteq L with m = ncols(M).
# Produces the *lower-left* HNF in place: the canonical basis occupies the
#   bottom m rows, lower triangular with reduced entries below each pivot.
# NOTE: AbstractAlgebra convention is upper-right
#   That's why we mark this with "_left" suffix
# This mirrors FLINT's fmpz_mat_hnf_modular_eldiv/nmod_mat_strong_echelon_form
#   (upper-right) by reflecting every index through the matrix center:
#   row r <-> n+1-r, col c <-> m+1-c.
#
# Phase 1 (echelon form modulo g):
#   step i clears column *above* the pivot.
# Phase 2 (strong echelon form) absorbs the implicit rows g*e_i:
#   the pivot becomes gcd(pivot, g), the column below it is reduced.
#   The leftover row (g/pivot)*row is merged into the diagonal positions up and to the left.
#   The lefover is the combination of the pivot row with g*e_i that survives modulo g.
# Phase 3 fills pivots that are still zero with g,
#   as those columns are generated by the implicit row alone.
function hnf_modular_eldiv_left!(M::MatElem{T}, g::T) where {T <: RingElem}

  # Mirrors FLINT's _n_stab (Storjohann's Stab):
  #   return t such that a + t*b is a unit modulo g
  function _stab(a::T, b::T, g::T)
    c = gcd(gcd(a, b), g)
    _, t = ppio(divexact(g, c), divexact(a, c))
    return t
  end

  # Mirrors FLINT's _n_unit:
  #   return a unit u modulo g with mod(u*a, g) == gcd(a, g)
  function _unit_mod(a::T, g::T)
    d, s, _ = gcdx(a, g)
    is_one(d) && return mod(s, g)
    l = divexact(g, d)
    t = _stab(s, l, g)
    return mod(s + t*l, g)
  end

  # In several places we need to store in the matrix the value of mod(t, g)
  #   where t is *temporary* variable used with mutating operations.
  # AbstractAlgebra mod for polynomials will return the same object t when
  #   its degree is less than degree of g.
  function _reduced_temp(a::T, g::T)
    r = mod(a, g)
    return r === a ? deepcopy(r) : r
  end

  # Replace the rows (a, b) with 2x2 unimodular transforms so that
  #   b[col] becomes 0 and a[col] becomes gcd(a[col], b[col]);
  #   columns above are reduced modulo g and columns below are left untouched.
  # With d = gcd(a[col], b[col]) = u*a[col] + v*b[col] the transform is
  #   (a; b) <- (u, v; -b[col]/d, a[col]/d) * (a; b),
  #   whose determinant is 1.
  function _combine!(a, b, col::Int, g::T)
    s1 = R(); s2 = R(); s3 = R()
    d, u, v = gcdx(a[col], b[col])
    u2 = -divexact(b[col], d)
    v2 =  divexact(a[col], d)
    for jc in 1:(col - 1)
      s1 = mul!(s1, u, a[jc]);  s1 = addmul!(s1, v, b[jc], s3)
      s2 = mul!(s2, u2, a[jc]); s2 = addmul!(s2, v2, b[jc], s3)
      a[jc] = _reduced_temp(s1, g)
      b[jc] = _reduced_temp(s2, g)
    end
    a[col] = d
    b[col] = zero(R)
    return nothing
  end

  @req !is_zero(g) "Modulus must be nonzero"
  n = nrows(M)
  m = ncols(M)
  @req n >= m "Matrix must have at least as many rows as columns"
  R = base_ring(M)

  # if g is unit, R^m == L and HNF is identity, sitting at the bottom m rows
  if is_unit(g)
    for i in 1:n, j in 1:m
      M[i, j] = (i == j + (n - m)) ? one(R) : zero(R)
    end
    return M
  end

  # canonicalize g
  g = divexact(g, canonical_unit(g))

  # reduce matrix modulo g
  for i in 1:n, j in 1:m
    M[i, j] = mod(M[i, j], g)
  end

  # scratch element for in-place arithmetic (_combine! keeps its own)
  t1 = R()

  # Phase 1: echelon form
  for i in 1:m
    pr = n + 1 - i   # pivot row
    pc = m + 1 - i   # pivot column

    # clear column pc above row pr by unimodular transforms (mod g)
    for kr in (pr - 1):-1:1
      # is already zero
      is_zero_entry(M, kr, pc) && continue

      # if not zero, check if pivot element is zero (update pivot)
      if is_zero_entry(M, pr, pc)
        swap_rows!(M, pr, kr)
        continue
      end

      # pivot M[pr, pc] is non-zero.
      fl, q = divides(M[kr, pc], M[pr, pc])
      if fl
        # pivot divides M[kr, pc]: do a plain row kr reduction
        q = neg!(q)
        for jc in 1:(pc - 1)
          t1 = mul!(t1, q, M[pr, jc])
          t1 = add!(t1, t1, M[kr, jc])
          M[kr, jc] = _reduced_temp(t1, g)
        end
        M[kr, pc] = zero(R)
      else
        # we need an unimodular transform for these two rows
        _combine!(view(M, pr, :), view(M, kr, :), pc, g)
      end
    end
  end

  # Phase 2: strong echelon form, absorbing the implicit rows g*e_pc
  extra_row = [zero(R) for _ in 1:m]
  for i in 1:m
    pr = n + 1 - i
    pc = m + 1 - i

    if !is_zero_entry(M, pr, pc)
      # make the pivot the canonical divisor gcd(M[pr, pc], g) of g
      u = _unit_mod(M[pr, pc], g)
      if !is_one(u)
        for jc in 1:pc
          t1 = mul!(t1, u, M[pr, jc])
          M[pr, jc] = _reduced_temp(t1, g)
        end
      end

      # reduce the entries of column pc below the pivot
      for kr in (pr + 1):n
        q = div(M[kr, pc], M[pr, pc])
        is_zero(q) && continue
        q = neg!(q)
        for jc in 1:pc
          t1 = mul!(t1, q, M[pr, jc])
          t1 = add!(t1, t1, M[kr, jc])
          M[kr, jc] = _reduced_temp(t1, g)
        end
      end

      # for a trivial pivot the leftover row vanishes modulo g
      is_one(M[pr, pc]) && continue

      c = divexact(g, M[pr, pc])
      for jc in 1:pc
        t1 = mul!(t1, c, M[pr, jc])
        extra_row[jc] = _reduced_temp(t1, g)
      end
    else
      # no pivot: the row content must still be pushed towards the diagonal
      for jc in 1:pc
        extra_row[jc] = deepcopy(M[pr, jc])
      end
    end

    # merge extra_row into the remaining diagonal positions;
    # each step zeroes extra_row at column dc, so whatever remains at the end lies in g*R^m
    for k in (i + 1):m
      dr = n + 1 - k
      dc = m + 1 - k
      is_zero(extra_row[dc]) && continue
      _combine!(view(M, dr, :), extra_row, dc, g)
    end
  end

  # Phase 3: pivots that are still zero are generated by g*e_pc alone
  for i in 1:m
    pr = n + 1 - i
    pc = m + 1 - i
    if is_zero_entry(M, pr, pc)
      M[pr, pc] = deepcopy(g)
    end
  end

  return M
end

# Specialization for Q(x)
# Here the bottleneck is coefficient swell, not degree, so the modular HNF
#   brings no benefit by itself: its reduction only bounds the degree in x.
# Worse, the extra gcd/mod work actively amplifies the coefficient swell, so
#   until we find a way to fight that directly we fall back to Kannan-Bachem.
# Empirically hnf_minors and hnf_via_popov are the clear winners on "trivial"
#   inputs, but as the degree grows (e.g. larger powers of an ideal) hnf_kb
#   becomes the clear winner.
# TODO: should we extend this to any polynomials over a characteristic-zero field?
#   (e.g. function fields over number fields)
function hnf_modular_eldiv_left!(M::MatElem{QQPolyRingElem}, ::QQPolyRingElem)
  reverse_cols!(M)
  AbstractAlgebra.hnf_kb!(M, similar(M, 0, 0))
  reverse_cols!(M)
  reverse_rows!(M)

  return M
end

###########################################################################################
#
#   Basis
#
###########################################################################################

@doc raw"""
    has_basis(A::GenOrdIdl) -> Bool

Return whether $A$ has a basis already computed.
"""
has_basis(A::GenOrdIdl) = isdefined(A, :basis)

function assure_has_basis(A::GenOrdIdl)
  if isdefined(A, :basis)
    return nothing
  else
    assure_has_basis_matrix(A)
    O = order(A)
    M = A.basis_matrix
    Ob = basis(O)
    B = Vector{elem_type(O)}(undef, degree(O))
    y = O()
    for i in 1:degree(O)
      z = O()
      for k in 1:degree(O)
        mul!(y,O(M[i, k]), Ob[k])
        add!(z, z, y)
      end
      B[i] = z
    end
    A.basis = B
    return nothing
  end
end

@doc raw"""
    basis(A::GenOrdIdl) -> Vector{GenOrdElem}

Return the basis of $A$.
"""
function Hecke.basis(A::GenOrdIdl; copy::Bool = true)
  assure_has_basis(A)
  if copy
    return deepcopy(A.basis)
  else
    return A.basis
  end
end


###########################################################################################
#
#   Basis Matrix
#
###########################################################################################

@doc raw"""
    basis_matrix(A::GenOrdIdl) -> Mat

Return the basis matrix of $A$.
"""
function Hecke.basis_matrix(A::GenOrdIdl{S, T}; copy::Bool = true) where {S, T}
  assure_has_basis_matrix(A)
  return (copy ? deepcopy(A.basis_matrix) : A.basis_matrix)::dense_matrix_type(elem_type(T))
end

function assure_has_basis_matrix(A::GenOrdIdl)
  if isdefined(A, :basis_matrix)
    return nothing
  end
  O = order(A)
  n = degree(O)

  if iszero(A)
    A.basis_matrix = zero_matrix(base_ring(O), n, n)
    return nothing
  end

  if has_princ_gen(A)
    A.basis_matrix = hnf(representation_matrix(A.princ_gen), :lowerleft)
    return nothing
  end

  @hassert :GenOrd 1 has_2_elem(A)

  V = hnf(reduce(vcat, [representation_matrix(x) for x in [O(A.gen_one),A.gen_two]]), :lowerleft)
  A.basis_matrix = sub(V, n+1:2*n, 1:n)
  return nothing
end

################################################################################
#
#  Basis matrix inverse
#
################################################################################

@doc raw"""
    has_basis_mat_inv(A::GenOrdIdl) -> Bool

Return whether $A$ knows its inverse basis matrix.
"""
has_basis_mat_inv(A::GenOrdIdl) = isdefined(A, :basis_mat_inv)

@doc raw"""
    basis_mat_inv(A::GenOrdIdl) -> FakeFracFldMat

Return the inverse of the basis matrix of $A$.
"""
function Hecke.basis_mat_inv(A::GenOrdIdl{S, T}; copy::Bool = true) where {S, T}
  assure_has_basis_mat_inv(A)
  if copy
    return deepcopy(A.basis_mat_inv)::dense_matrix_type(elem_type(base_field(field(order(A)))))
  else
    return A.basis_mat_inv::dense_matrix_type(elem_type(base_field(field(order(A)))))
  end
end

function assure_has_basis_mat_inv(A::GenOrdIdl)
  if isdefined(A, :basis_mat_inv)
    return nothing
  else
    A.basis_mat_inv = inv(change_base_ring(base_field(field(order(A))), basis_matrix(A)))
    return nothing
  end
end

###########################################################################################
#
#   Misc
#
###########################################################################################

(O::GenOrd)(p::PolyRingElem) = O(O.F(p))
Hecke.is_commutative(O::GenOrd) = true

Nemo.elem_type(::Type{GenOrd}) = GenOrdElem

function Hecke.hnf(x::T, shape::Symbol =:upperright) where {T <: MatElem}
  if shape == :lowerleft
    h = hnf(reverse_cols(x))
    reverse_cols!(h)
    reverse_rows!(h)
    return h::T
  end
  return hnf(x)::T
end

################################################################################
#
#  Binary Operations
#
################################################################################

function Base.:(+)(a::GenOrdIdl{S, T}, b::GenOrdIdl{S, T}) where {S, T}
  @req order(a) === order(b) "Ideals must have same order"

  is_zero(a) && return b
  is_zero(b) && return a
  is_one(a)  && return a
  is_one(b)  && return b

  O = order(a)

  g = gcd(minimum(a; copy = false), minimum(b; copy = false))
  V = vcat(basis_matrix(a; copy = false), basis_matrix(b; copy = false))
  V = hnf_modular_eldiv_left!(V, g)
  return ideal(O, V; M_in_hnf = true)
end

function Base.:(==)(a::GenOrdIdl{S, T}, b::GenOrdIdl{S, T}) where {S, T}
  return basis_matrix(a; copy = false) == basis_matrix(b; copy = false)
end
function Base.isequal(a::GenOrdIdl{S, T}, b::GenOrdIdl{S, T}) where {S, T}
  return a == b
end

function Base.:(*)(a::GenOrdIdl{S, T}, b::GenOrdIdl{S, T}) where {S, T}
  @req order(a) === order(b) "Ideals must have same order"

  is_zero(a) && return a
  is_zero(b) && return b
  is_one(a)  && return b
  is_one(b)  && return a

  O = order(a)
  n = degree(O)

  g = minimum(a; copy = false) * minimum(b; copy = false)
  Ma = basis_matrix(a; copy = false)
  Mb = basis_matrix(b; copy = false)

  blocks = [Mb * _representation_matrix(O, view(Ma, i, 1:n)) for i in 1:n]
  V = hnf_modular_eldiv_left!(reduce(vcat, blocks), g)
  return ideal(O, V; M_in_hnf = true)
end

@doc raw"""
    intersect(x::GenOrdIdl, y::GenOrdIdl) -> GenOrdIdl

Returns $x \cap y$.
"""
function Base.intersect(a::GenOrdIdl{S, T}, b::GenOrdIdl{S, T}) where {S, T}
  @req order(a) === order(b) "Ideals must have same order"

  is_zero(a) && return a
  is_zero(b) && return b
  is_one(a)  && return b
  is_one(b)  && return a

  # [A A ; 0 B] lower left HNF gives intersection in the top left block
  O = order(a)
  n = degree(O)

  g = lcm(minimum(a; copy = false), minimum(b; copy = false))
  Ma = basis_matrix(a; copy = false)
  Mb = basis_matrix(b; copy = false)
  V = vcat(hcat(Ma, Ma), hcat(zero_matrix(base_ring(O), n, n), Mb))
  H = sub(hnf_modular_eldiv_left!(V, g), 1:n, 1:n)
  return ideal(O, H; M_in_hnf = true)
end

################################################################################
#
#  Powering
#
################################################################################

function Base.:(^)(A::GenOrdIdl, e::Int)
  O = order(A)
  if e == 0
    return ideal(O, one(O))
  elseif e == 1
    return A
  elseif e < 0
    return inv(A)^(-e)
  end
  return Base.power_by_squaring(A, e)
end


################################################################################
#
#  Ad hoc multiplication
#
################################################################################

# Multiplying an integral ideal by a *base ring* scalar is equivalent to
#   scaling the ideal basis matrix.
# Internal helper for base-ring scalar case
function _ideal_by_scaling_matrix(c, I::GenOrdIdl)
  O = order(I)
  # we must ensure canonical form, to keep HNF canonical
  c = _make_canonical_in(O, c)

  is_zero(c) && return ideal(O, c)
  is_one(c) && return I
  return ideal(O, c * basis_matrix(I; copy = false); M_in_hnf = true)
end

# This is the check for "scalar is in the base ring"
# Since x is GenOrdElem, it is integral, so we need to check if it is in the base field
function _is_in_base_field(x::GenOrdElem)
  a = data(x)
  for i in 1:degree(parent(a)) - 1
    is_zero(coeff(a, i)) || return false
  end
  return true
end

function Base.:*(x::GenOrdElem, O::GenOrd)
  return ideal(O, x)
end

function Base.:*(x::GenOrdElem, I::GenOrdIdl{S, T}) where {S, T}
  O = order(I) # note that this has concrete type for type inference
  @req parent(x) === O "Element and ideal must belong to the same order"

  if _is_in_base_field(x)
    c, den = integral_split(coeff(data(x), 0), base_ring(O))
    @assert is_one(den)
    return _ideal_by_scaling_matrix(c, I)
  end

  return ideal(O, x) * I
end

Base.:*(x::GenOrdIdl, y::GenOrdElem) = y * x

function Hecke.colon(a::GenOrdIdl{S, T}, b::GenOrdIdl{S, T}) where {S, T}
  @req order(a) === order(b) "Ideals must lie in the same order"
  O = order(a)
  Kt = base_field(field(O))
  B = basis(b)
  bmatinv = basis_mat_inv(a; copy = false)

  # For each generator b_i of b, compute (mult-by-b_i) * A^{-1} = M_i / d_i,
  #   and concatenate the M_i side-by-side into one matrix m with common denominator d.
  mult_matrix(x) = change_base_ring(Kt, representation_matrix(x)) * bmatinv
  base_num_den = [integral_split(mult_matrix(b_i), coefficient_ring(O)) for b_i in B]
  d = reduce(lcm, (den for (_, den) in base_num_den))
  m = reduce(hcat, (num * div(d, den) for (num, den) in base_num_den))

  # m is shape n x (n*|B|). HNF on its transpose gives a basis in the first n rows
  #   so we transpose back to columns.
  m = transpose(sub(hnf(transpose(m)), 1:degree(O), 1:degree(O)))
  # Lift, divide by d, invert: that's (a:b) as a fractional ideal.
  basis_mat = inv(divexact(change_base_ring(Kt, m), Kt(d)))
  return GenOrdFracIdl(O, basis_mat)
end

# If I is not coprime to the conductor of O in the maximal order, then this might
# not be an inverse.
function inv(A::GenOrdIdl)
  O = order(A)
  return colon(O(1)*O, A)
end


################################################################################
#
#  Exact Division
#
################################################################################


function Hecke.divexact(A::GenOrdIdl, b::RingElem)
  is_zero(A) && return A

  O = order(A)
  b = _make_canonical_in(O, b)
  is_unit(b) && return A

  bm = divexact(basis_matrix(A; copy = false), b)
  B = ideal(O, bm; M_in_hnf = true)

  if has_princ_gen(A)
    # Coerce the base-ring scalar b through the base field before embedding it
    #   into O.F before dividing.
    bF = O.F(base_field(O.F)(b))
    B.princ_gen = O(divexact(O.F(A.princ_gen), bF))
  end

  return B
end


function has_minimum(A::GenOrdIdl)
  return isdefined(A, :minimum)
end

function Hecke.minimum(A::GenOrdIdl; copy::Bool = true)
  assure_has_minimum(A)
  if copy
    return deepcopy(A.minimum)::elem_type(base_ring(order(A)))
  else
    return A.minimum::elem_type(base_ring(order(A)))
  end
end

function assure_has_minimum(A::GenOrdIdl)
  if has_minimum(A)
    return nothing
  end

  O = order(A)

  if isone(basis(O; copy = false)[1])
    A.minimum = deepcopy(basis_matrix(A; copy = false)[1, 1])
  else
    M = basis_matrix(A; copy = false)
    d = prod([M[i, i] for i = 1:nrows(M)])
    v = transpose(matrix(map(base_ring(O), coordinates(O(d)))))
    fl, s = can_solve_with_solution(M, v, side = :left)
    @assert fl
    den = denominator(s[1]//d)
    for i = 2:ncols(s)
      den = lcm(den, denominator(s[i]//d))
    end

    A.minimum = _make_canonical_in(O, den)
  end

  return nothing
end

################################################################################
#
#  Norm
#
################################################################################

@doc raw"""
    has_norm(A::GenOrdIdl) -> Bool

Return whether $A$ knows its norm.
"""
function has_norm(A::GenOrdIdl)
  return isdefined(A, :norm)
end

function assure_has_norm(A::GenOrdIdl)
  if has_norm(A)
    return nothing
  end

  A.norm = _make_canonical_in(order(A), det(basis_matrix(A; copy = false)))
  return nothing
end

@doc raw"""
    norm(A::GenOrdIdl) -> RingElem

Return the norm of $A$, that is, the cardinality of $\mathcal O/A$, where
$\mathcal O$ is the order of $A$.
"""
function Hecke.norm(A::GenOrdIdl; copy::Bool = true)
  assure_has_norm(A)
  if copy
    return deepcopy(A.norm)::elem_type(base_ring(order(A)))
  else
    return A.norm::elem_type(base_ring(order(A)))
  end
end

################################################################################
#
#  Numerator and Denominator
#
################################################################################

function Hecke.numerator(a::Generic.FunctionFieldElem, O::GenOrd)
  return integral_split(a,O)[1]
end

function Hecke.denominator(a::Generic.FunctionFieldElem, O::GenOrd)
  return integral_split(a,O)[2]
end

################################################################################
#
#  Principal Generator
#
################################################################################

@doc raw"""
    has_princ_gen(A::GenOrdIdl) -> Bool

Returns whether $A$ knows if it is generated by one element.
"""
function has_princ_gen(A::GenOrdIdl)
  return isdefined(A, :princ_gen)
end

################################################################################
#
#  Reduction of element modulo ideal
#
################################################################################

function Hecke.mod(x::GenOrdElem, y::GenOrdIdl)
  parent(x) !== order(y) && error("GenOrds of element and ideal must be equal")
  # this function assumes that HNF is lower left
  # !!! This must be changed as soon as HNF has a different shape

  O = order(y)
  d = degree(O)
  a = base_ring(O).(coordinates(x))

  c = basis_matrix(y)
  t = O.R(0)
  for i in 1:d
    t = div(a[i], c[i,i])
    for j in 1:i
      a[j] = a[j] - t*c[i,j]
    end
  end
  z = O([a[i] for i in 1:length(a)])
  return z
end

################################################################################
#
#  Residue field
#
################################################################################

function Hecke.residue_field(R::fpPolyRing, p::fpPolyRingElem)
  K, _ = finite_field(p,"o")
  return K, MapFromFunc(R, K, x->K(x), y->R(y))
end

function Hecke.residue_field(R::FqPolyRing, p::FqPolyRingElem)
  return Nemo._residue_field(p, absolute = false)
end

################################################################################
#
#  Factorization
#
################################################################################

function Hecke.index(O::GenOrd)
  return is_equation_order(O) ? O.R(1) : O.R(det(basis_matrix_inverse(O)))
end

function prime_dec_nonindex(O::GenOrd{S, T}, p::RingElem, degree_limit::Int = 0, lower_limit::Int = 0) where {S, T}
  @req parent(p) === base_ring(O) "p must come from the base ring of O"

  F = field(O)
  B = base_field(F)
  a = gen(F)

  K, mK = residue_field(base_ring(O), p)

  fmodp = map_coefficients(defining_polynomial(O.F); cached = false) do c
    num, den = integral_split(c, base_ring(O))
    mK(num) // mK(den)
  end
  fact = factor(fmodp)

  result = Vector{Tuple{GenOrdIdl{S, T}, Int}}(undef, length(fact))
  for (i, (fac, e)) in enumerate(fact)
    f = degree(fac)
    facnew = map_coefficients(y -> B(preimage(mK, y)), fac, cached = false)
    b = O(facnew(a))
    # We want a P-normal two-element presentation, i.e. v_P(b) = 1.
    # Since we are in the case of p not dividing the index, we have a good candidate b = g(a).
    #
    # v_P(<p,b>) = min[v_P(p), v_P(b)] = 1.
    # Ramified case   (e > 1): v_P(p) = e > 1, so v_P(b) = 1 is forced.
    # Unramified case (e = 1): v_P(b) can exceed 1, in which case
    #   v_P(b + p) = min(v_P(b), 1) = 1
    # For other primes Q over p, v_Q(b) > 0 would give v_Q(<p, b>) > 0,
    #   giving <p,b> subset of Q, contradicting <p, b> = P.
    #
    # In the unramified case we need to check if v_P(b) == 1.
    # One possibility is to check if p*N(P) = p^{f+1} divides N(b)
    #   and if it doesn't, we must have v_P(b) == 1.
    # Unlike the number field case, b can be zero (single inert prime over p),
    #   which is also covered by adding p.
    if e == 1 && (is_zero(b) || divides(norm(b), p^(f + 1))[1])
      b = b + O(p)
    end

    I = ideal(O, p, b)
    I.is_prime = 1
    I.splitting_type = e, f
    I.norm = p^f
    I.minimum = p
    result[i] = (I,e)
  end
  return result
end

function Hecke.valuation(A::GenOrdIdl{S, T}, p::GenOrdIdl{S, T}) where {S, T}
  O = order(A)
  e = 0
  if has_2_elem(p)
    beta = Hecke.numerator(inv(O.F(p.gen_two)),O)
    newA = GenOrdFracIdl(beta*A,p.gen_one)
    while is_integral(newA)
      e += 1
      newA = GenOrdFracIdl(numerator(beta*newA; copy = false), p.gen_one)
    end
  else
    newA = Hecke.colon(A,p)
    while is_integral(newA)
      e+=1
      newA = Hecke.colon(newA,GenOrdFracIdl(p))
    end
  end
  return e
end


function Hecke.factor(A::GenOrdIdl{S, T}) where {S, T}
  O = A.order
  N = norm(A)
  factors = factor(N)
  primes = Dict{GenOrdIdl{S, T},Int}()
  for (f,e) in factors
    for (p,r) in prime_decomposition(O,f)
      p_val = valuation(A, p)
      if p_val != 0
        primes[p] = p_val
      end
    end
  end
  return primes
end

function prime_decomposition(O::GenOrd{S, T}, p::RingElem, degree_limit::Int = degree(O), lower_limit::Int = 0; cached::Bool = true) where {S, T}
  # Fast path needs:
  # 1. well-defined equation order: we need defining polynomial to be "nice",
  #    that is, monic and integral
  # 2. finite maximal order setting, since index is ill-defined for KInftyRing
  # 3. p coprime to index
  # Note: for non-nice polynomials the index has a denominator.
  #       We could check divisibility by p of both numerator and denominator,
  #       but that is a bit hacky, so we mimic number fields and instead
  #       check that the defining polynomial is nice.
  if !isa(base_ring(O), KInftyRing) &&
     is_defining_polynomial_nice(O.F) &&
     !(divides(index(O), p)[1])
    return prime_dec_nonindex(O, p, degree_limit, lower_limit)
  else
    return prime_dec_gen(O, p, degree_limit, lower_limit)
  end
end

# TODO: prime_dec_gen currently does NOT set gen_two
# TODO: we should mimic number fields by adding a search for a uniformizer
function prime_dec_gen(O::GenOrd{S, T}, p::RingElem, degree_limit::Int = degree(O), lower_limit::Int = 0) where {S, T}
  Ip = pradical(O, p)
  lp = _decomposition(O, ideal(O, p), Ip, ideal(O, one(O)), p)
  #=z = Tuple{ideal_type(O), Int}[]
  for (Q, e) in lp
    if degree(Q) <= degree_limit && degree(Q) >= lower_limit
      push!(z, (Q, e))
    end
  end
  return z
  =#
  return lp
end

function residue_field(R::PolyRing{QQBarFieldElem}, p::PolyRingElem{QQBarFieldElem})
  @assert degree(p) == 1
  @assert is_monic(p)
  c = -coeff(p, 0)
  K = base_ring(R)
  f = MapFromFunc(R, K, q -> q(c), x -> R(x))
  return K, f
end

function Hecke.pradical(O::GenOrd, p::RingElem)
  R, mR = residue_field(parent(p), p)

#  @assert characteristic(F) == 0 || (isfinite(F) && characteristic(F) > degree(O))
  if characteristic(R) == 0 || characteristic(R) > degree(O)
    @vprintln :GenOrd 1 "using trace-radical for $p"
    rad = radical_basis_trace
  elseif isa(R, Generic.RationalFunctionField)
    @vprintln :GenOrd 1 "non-perfect case for radical for $p"
    rad = radical_basis_power_non_perfect
  else
    @vprintln :GenOrd 1 "using radical-by-power for $p"
    rad = radical_basis_power
  end
  return ideal(O, rad(O,p); M_in_hnf = true)
end

# WARNING: TI is unused. I guess the idea is to keep signature same as AbsNumField case
function _decomposition(O::GenOrd{S, T}, I::GenOrdIdl{S, T}, Ip::GenOrdIdl{S, T}, TI::GenOrdIdl{S, T}, p::RingElem) where {S, T}
  #I is an ideal lying over p
  #T is contained in the product of all the prime ideals lying over p that do not appear in the factorization of I
  #Ip is the p-radical
  Ip1 = Ip + I
  A, OtoA = StructureConstantAlgebra(O, Ip1, p)
  AtoO = pseudo_inv(OtoA)
  ideals, _ = _from_algs_to_ideals(A, OtoA, AtoO, Ip1, p)
  for j in 1:length(ideals)
    P = ideals[j][1]
    f = P.splitting_type[2]
    e = valuation(ideal(O, p), P)
    P.splitting_type = e, f
    ideals[j] = (P,e)
  end
  return ideals
end

function StructureConstantAlgebra(O::GenOrd, I::GenOrdIdl, p::RingElem)
  FQ, phi = residue_field(base_ring(O), p)
  StructureConstantAlgebra(O, I, p, phi)
end

function StructureConstantAlgebra(O::GenOrd, I::GenOrdIdl, p::RingElem, phi)
  @assert order(I) === O

  n = degree(O)
  bmatI = basis_matrix(I)

  basis_elts = Vector{Int}()
  for i = 1:n
    if is_coprime(bmatI[i, i], p)
      continue
    end

    push!(basis_elts, i)
  end

  r = length(basis_elts)
  FQ = codomain(phi)

  if r == 0
    A = zero_algebra(FQ)

    local _image_zero

    let A = A
      function _image_zero(a::GenOrdElem)
        return A()
      end
    end

    local _preimage_zero

    let O = O
      function _preimage_zero(a::AssociativeAlgebraElem)
        return O()
      end
    end

    OtoA = Hecke.AbsOrdToAlgAssMor{typeof(O), elem_type(FQ)}(O, A, _image_zero, _preimage_zero)
    return A, OtoA
  end

  BO = basis(O)
  mult_table = Array{elem_type(FQ), 3}(undef, r, r, r)
  for i = 1:r
    M = representation_matrix(BO[basis_elts[i]])
    #TODO: write version of reduce rows mod hnf
    if r != degree(O)
      M = reduce_rows_mod_hnf!(M, bmatI, basis_elts)
    end
    for j = 1:r
      for k = 1:r
        mult_table[i, j, k] = phi(M[basis_elts[j], basis_elts[k]])
      end
    end
  end

  if isone(BO[1])
    one = [zero(FQ) for _ in 1:r]
    one[1] = FQ(1)
    A = StructureConstantAlgebra(FQ, mult_table, one)
  else
    A = StructureConstantAlgebra(FQ, mult_table)
  end
  if is_commutative(O)
    A.is_commutative = 1
  end

  local _image

  let I = I, A = A, basis_elts = basis_elts, FQ = FQ
    function _image(a::GenOrdElem)
      c = coordinates(mod(a, I))
      return A([phi(O.R(c[i])) for i in basis_elts ])
    end
  end

  local _preimage

  let BO = BO, basis_elts = basis_elts, r = r
    function _preimage(a::AssociativeAlgebraElem)
      ca = coefficients(a)
      return sum(preimage(phi, ca[i]) * BO[basis_elts[i]] for i in 1:length(ca))
    end
  end

  OtoA = GenOrdToAlgAssMor{typeof(O), elem_type(FQ)}(O, A, _image, _preimage)

  return A, OtoA
end

# Reduces the rows of M in `rows` modulo N in place.
# Assumes that N is in lowerleft HNF.
function reduce_rows_mod_hnf!(M::MatElem, N::MatElem, rows::Vector{Int})
  for i in rows
    for j = ncols(M):-1:1
      if iszero(M[i, j])
        continue
      end

      t = div(M[i, j], N[j, j])
      for k = 1:j
        M[i, k] = M[i, k] - t*N[j, k]
      end
    end
  end
  return M
end

################################################################################
#
#   Degree and ramification index
#
################################################################################

@doc raw"""
    degree(P::GenOrdIdl) -> Int
    inertia_degree(P::GenOrdIdl) -> Int

The inertia degree of the prime-ideal $P$.
"""
function degree(P::GenOrdIdl)
  @assert is_prime(P)
  return P.splitting_type[2]
end

inertia_degree(P::GenOrdIdl) = degree(P)

@doc raw"""
    ramification_index(P::GenOrdIdl) -> Int

The ramification index of the prime-ideal $P$.
"""
function ramification_index(P::GenOrdIdl)
  @assert is_prime(P)
  return P.splitting_type[1]
end


################################################################################
#
#  Primality testing
#
################################################################################

@doc raw"""
    is_prime_known(A::GenOrdIdl) -> Bool

Returns whether $A$ knows if it is prime.
"""
function is_prime_known(A::GenOrdIdl)
  return A.is_prime != 0
end

@doc raw"""
    is_prime(A::GenOrdIdl) -> Bool

Returns whether $A$ is a prime ideal.
"""
function is_prime(A::GenOrdIdl)
  if is_prime_known(A)
    return A.is_prime == 1
  elseif minimum(A) == 0
    A.is_prime = 1
    return true
  end

  lp = factor(A)
  for (P, e) in lp
    if norm(A) != norm(P)
      continue
    end

    # from factorization we know already that A is in P
    # TODO: for non-maximal orders we need to check both generators
    # TODO: though most of our code around primes assumes maximal order
    PinA = if has_2_elem(P)
      P.gen_two in A
    else
      A == P
    end

    if PinA
      A.is_prime = 1
      A.splitting_type = P.splitting_type
      return true
    end
  end
  A.is_prime = 2
  return false
end

################################################################################
#
#  Inclusion of elements in ideals
#
################################################################################

@doc raw"""
    in(x::GenOrdElem, y::GenOrdIdl)

Returns whether $x$ is contained in $y$.
"""
function in(x::GenOrdElem, y::GenOrdIdl)
  @req parent(x) === order(y) "Both element and ideal must come from the same order"
  return containment_by_matrices(x, y)
end

function containment_by_matrices(x::GenOrdElem, y::GenOrdIdl)
  A = basis_mat_inv(y)
  den = lcm(collect(map(denominator, A)))
  kx = base_ring(order(y))
  num = map_entries(kx, A*den)
  R = residue_ring(kx, den; cached = false)[1]
  M = map_entries(R, num)
  # coordinates(x) are in base field: lift through O.R
  coords = map(c -> numerator(c, kx), coordinates(x))
  v = matrix(R, 1, degree(parent(x)), coords)
  #mul!(v, v, M) This didn't work
  v = v*M
  return iszero(v)
end

###############################################################################
#
#  Decomposition type using polygons
#
###############################################################################

function _from_algs_to_ideals(A::StructureConstantAlgebra{T}, OtoA::Map, AtoO::Map, Ip1, p::RingElem) where {T}

  O = order(Ip1)
  n = degree(O)
  R = O.R
  @vprintln :GenOrd 1 "Splitting the algebra"
  AA = Hecke.decompose(A)
  @vprintln :GenOrd 1 "Done"
  ideals = Vector{Tuple{typeof(Ip1), Int}}(undef, length(AA))
  N = basis_matrix(Ip1; copy = false)
  list_bases = Vector{Vector{Vector{elem_type(R)}}}(undef, length(AA))
  for i = 1:length(AA)
    l = Vector{Vector{elem_type(R)}}(undef, dim(AA[i][1]))
    for j = 1:length(l)
      v = map(O.R,coordinates(AtoO(AA[i][2](AA[i][1][j]))))
      l[j] = [v[o] for o in 1:length(v)]
    end
    list_bases[i] = l
  end
  for i = 1:length(AA)
    B = AA[i][1]
    BtoA = AA[i][2]
    #we need the kernel of the projection map from A to B.
    #This is given by the basis of all the other components.
    f = dim(B)
    N1 = vcat(N, zero_matrix(R, dim(A) - f, n))
    t = 1
    for j = 1:length(AA)
      if j == i
        continue
      end
      for s = 1:length(list_bases[j])
        b = list_bases[j][s]
        for j = 1:degree(O)
          N1[n + t, j] = b[j]
        end
        t += 1
      end
    end

    P = ideal(O, hnf(N1, :lowerleft); M_in_hnf = true)
    P.minimum = p
    P.norm = p^f
    P.splitting_type = (0, f)
    P.is_prime = 1
    fromOtosimplealgebra = compose(OtoA, pseudo_inv(BtoA))
    #compute_residue_field_data!(P, fromOtosimplealgebra)
    ideals[i] = (P, 0)
  end
  return ideals, AA
end


################################################################################
#
#  GenOrdToAlgAssMor type
#
################################################################################

mutable struct GenOrdToAlgAssMor{S, T} <: Map{S, StructureConstantAlgebra{T}, Hecke.HeckeMap, Any}#GenOrdToAlgAssMor}
  header::Hecke.MapHeader

  function GenOrdToAlgAssMor{S, T}(O::S, A::StructureConstantAlgebra{T}, _image::Function, _preimage::Function) where {S <: GenOrd, T}
    z = new{S, T}()
    z.header = Hecke.MapHeader(O, A, _image, _preimage)
    return z
  end
end

function GenOrdToAlgAssMor(O::GenOrd, A::StructureConstantAlgebra{T}, _image, _preimage) where {T}
  return GenOrdToAlgAssMor{typeof(O), T}(O, A, _image, _preimage)
end

################################################################################
#
#  Misc.
#
################################################################################

function Hecke.characteristic(R::EuclideanRingResidueField{<:Hecke.GenOrdElem{<:Generic.FunctionFieldElem}})
  return characteristic(function_field(base_ring(R)))
end

mutable struct GenOrdToFqField{S, T} <: Map{S, T, Hecke.HeckeMap, Any}#GenOrdToFqField}
  header::Hecke.MapHeader

  function GenOrdToFqField{S, T}(O::S, A::T, _image::Function, _preimage::Function) where {S <: GenOrd, T}
    z = new{S, T}()
    z.header = Hecke.MapHeader(O, A, _image, _preimage)
    return z
  end
end

function Nemo._residue_field(f::PolyRingElem{<:NumFieldElem})
  Kt = parent(f)
  L, b = number_field(f, "a"; cached = false)
  return L, MapFromFunc(Kt, L, x -> L(x), y -> Kt(y))
end

function residue_field(O::GenOrd, P::GenOrdIdl, check::Bool = true)
  a, g, b, phi = get_residue_field_data(P)::Tuple{elem_type(O),
                                                  poly_type(base_ring(O)),
                                                  Vector{dense_matrix_type(base_ring(O))},
                                                  Any} # not optimal
  gg = map_coefficients(phi, g)
  bb = map_entries.(phi, b)
  K = base_ring(parent(gg))
  F, KtoF = Nemo._residue_field(gg)
  d = degree(O)
  imgofbas = [KtoF(parent(gg)(bb[i][1, :])) for i in 1:d]
  powersofa = powers(a, degree(g))

  _image = function(x::GenOrdElem)
    @assert parent(x) === O
    c = base_ring(O).(coordinates(x))
    return sum(phi(c[i]) * imgofbas[i] for i in 1:d)
  end

  _preimage = function(x)
    @assert parent(x) === F
    return sum(preimage(phi, coeff(x, i - 1)) * powersofa[i] for i in 1:degree(g))
  end

  return F, GenOrdToFqField{typeof(O), typeof(F)}(O, F, _image, _preimage)
end
