################################################################################
#
#  Constructors
#
################################################################################

# Two-element form requires the first generator to be the element of the coefficient ring.
# Testing the parent of first generator is too strict: for example literal 2
#   is not a ZZRingElem; similarly for t and 1//t both having k(t) as a parent,
#   t is in k[t] and 1//t is in KInftyRing (can be used as first generators
#   in finite/infinite orders).
function _as_coefficient_ring_elem(O::GenOrd, a::RingElement)
  R = base_ring(O)

  # if already in coefficient ring: can be used directly
  parent(a) === R && return a
  # if not in the base field, cannot be used for two-element representation
  if parent(a) !== base_field(field(O))
    return nothing
  end

  num, den = integral_split(a, R)
  return is_unit(den) ? divexact(num, den) : nothing
end
# no integral_split for IntegerUnion, do coersion directly
_as_coefficient_ring_elem(O::GenOrd, a::IntegerUnion) = base_ring(O)(a)

function ideal(O::GenOrd, a::RingElement, b::GenOrdElem)
  @req parent(b) === O "generators must belong to the given order"

  g = _as_coefficient_ring_elem(O, a)
  if g === nothing
    return ideal(O, elem_type(O)[O(a), b])
  else
    return is_zero(g) ? GenOrdIdl(O, b) : GenOrdIdl(O, g, b)
  end
end

ideal(O::GenOrd, a::RingElement, b::RingElement) = ideal(O, a, O(b))
ideal(O::GenOrd, a::GenOrdElem, b::RingElement) = ideal(O, elem_type(O)[a, O(b)])
ideal(O::GenOrd, a::GenOrdElem, b::GenOrdElem) = ideal(O, elem_type(O)[a, b])

ideal(O::GenOrd, a::RingElement) = GenOrdIdl(O, O(a))
ideal(O::GenOrd, a::GenOrdElem) = GenOrdIdl(O, a)

function ideal(O::GenOrd, v::Vector{<:GenOrdElem})
  @req all(x -> parent(x) === O, v) "generators must belong to the given order"
  isempty(v) && return ideal(O, zero(O))

  return GenOrdIdl(O, v)
end


function ideal(O::GenOrd, M::MatElem; M_in_hnf::Bool = false)
  n = degree(O)
  @req base_ring(M) === coefficient_ring(O) "matrix must be over the coefficient ring of O"
  @req ncols(M) == n "matrix must have exactly degree(O) = $n columns"
  @req nrows(M) >= n "matrix must have at least degree(O) = $n rows"

  H = M_in_hnf ? M : hnf(M, :lowerleft)
  @hassert :GenOrd 1 !M_in_hnf || H == hnf(H, :lowerleft)

  # the canonical lower-left HNF basis lives in the bottom n rows
  # also ensure that we materialize a view
  if nrows(H) > n || H isa AbstractAlgebra.Generic.MatSpaceView
    H = sub(H, nrows(H) - n + 1:nrows(H), 1:n)
  end

  return GenOrdIdl(O, H)
end

function AbstractAlgebra.zero(a::GenOrdIdl)
  O = a.order
  return GenOrdIdl(O, O(0))
end

has_2_elem(A::GenOrdIdl) = isdefined(A, :gen_two)

function is_zero(I::GenOrdIdl)
  if I.is_zero == 0
    if isdefined(I, :princ_gen)
      I.is_zero = is_zero(I.princ_gen) ? 1 : 2
    elseif isdefined(I, :gen_one) && isdefined(I, :gen_two)
      I.is_zero = is_zero(I.gen_one) && is_zero(I.gen_two) ? 1 : 2
    else
      @hassert :GenOrd 1 isdefined(I, :basis_matrix)
      # NOTE: assure_has_basis_matrix calls is_zero, so read field directly
      I.is_zero = is_zero(I.basis_matrix) ? 1 : 2
    end
  end

  return I.is_zero == 1
end

@doc raw"""
    is_one(A::GenOrdIdl) -> Bool
    is_unit(A::GenOrdIdl) -> Bool

Tests if $A$ is the trivial ideal generated by $1$.
"""
function is_one(I::GenOrdIdl)
  if isdefined(I, :norm)
    return is_one(norm(I; copy = false))
  end
  return is_one(minimum(I; copy = false))
end

is_unit(I::GenOrdIdl) = isone(I)

################################################################################
#
#  Basic field access
#
################################################################################

@doc raw"""
    order(x::GenOrdIdl) -> GenOrd

Return the order, of which $x$ is an ideal.
"""
Hecke.order(a::GenOrdIdl) = a.order

################################################################################
#
#  Copy
#
################################################################################

function Base.deepcopy_internal(I::GenOrdIdl{S, T}, dict::IdDict) where {S, T}
  J = GenOrdIdl(order(I))
  for f in fieldnames(typeof(I))
    f === :order && continue
    if isdefined(I, f)
      setfield!(J, f, Base.deepcopy_internal(getfield(I, f), dict))
    end
  end
  return J
end

################################################################################
#
#  Hash
#
################################################################################

function Base.hash(I::GenOrdIdl, h::UInt)
  b = 0x11ba13ff011affd1%UInt
  return xor(b, hash(basis_matrix(I; copy = false), hash(order(I), h)))
end

################################################################################
#
#  IO
#
################################################################################

function show(io::IO, id::GenOrdIdl)
  print(io, "Ideal of ", id.order)
  if has_2_elem(id)
    print(io, "\nGenerators: <", id.gen_one, ", ", id.gen_two, ">" )
  else
    print(io, "\nGenerators: <no 2-elts present>");
  end
  if has_norm(id)
    print(io, "\nNorm: ", id.norm);
  end
  if has_minimum(id)
    print(io, "\nMinimum: ", id.minimum);
  end
  if isdefined(id, :princ_gen)
    print(io, "\nPrincipal generator ", id.princ_gen)
  end
  if isdefined(id, :basis_matrix)
    print(io, "\nBasis_matrix \n", id.basis_matrix)
  end
end

################################################################################
#
#  2-element normal presentation
#
################################################################################

function defines_2_normal(A::GenOrdIdl)
  has_2_elem(A) || return false

  O = order(A)
  m = A.gen_one

  # normality demands both generators to be non-zero
  (is_zero(m) || is_zero(A.gen_two)) && return false
  # for m unit, A = O; normality is vacuous
  is_unit(m) && return true

  # this is Pohst-Zassenhaus, lemma 3.22
  m_alpha = _minimum_principal(O, A.gen_two)
  g = gcd(m, m_alpha)
  return is_unit(gcd(m, divexact(m_alpha, g)))
end

function has_2_elem_normal(A::GenOrdIdl)
  if isdefined(A, :gens_normal)
    return is_unit(A.gen_one) || !is_unit(A.gens_normal)
  end
  if has_2_elem(A) && defines_2_normal(A)
    A.gens_normal = A.gen_one
    return true
  end
  return false
end


###########################################################################################
#
#   Basis
#
###########################################################################################

@doc raw"""
    has_basis(A::GenOrdIdl) -> Bool

Return whether $A$ has a basis already computed.
"""
has_basis(A::GenOrdIdl) = isdefined(A, :basis)

function assure_has_basis(A::GenOrdIdl)
  if isdefined(A, :basis)
    return nothing
  else
    assure_has_basis_matrix(A)
    O = order(A)
    M = A.basis_matrix
    Ob = basis(O)
    B = Vector{elem_type(O)}(undef, degree(O))
    y = O()
    for i in 1:degree(O)
      z = O()
      for k in 1:degree(O)
        mul!(y,O(M[i, k]), Ob[k])
        add!(z, z, y)
      end
      B[i] = z
    end
    A.basis = B
    return nothing
  end
end

@doc raw"""
    basis(A::GenOrdIdl) -> Vector{GenOrdElem}

Return the basis of $A$.
"""
function Hecke.basis(A::GenOrdIdl; copy::Bool = true)
  assure_has_basis(A)
  if copy
    return deepcopy(A.basis)
  else
    return A.basis
  end
end


###########################################################################################
#
#   Basis Matrix
#
###########################################################################################

@doc raw"""
    basis_matrix(A::GenOrdIdl) -> Mat

Return the basis matrix of $A$.
"""
function Hecke.basis_matrix(A::GenOrdIdl{S, T}; copy::Bool = true) where {S, T}
  assure_has_basis_matrix(A)
  return (copy ? deepcopy(A.basis_matrix) : A.basis_matrix)::dense_matrix_type(elem_type(T))
end

function assure_has_basis_matrix(A::GenOrdIdl)
  if isdefined(A, :basis_matrix)
    return nothing
  end
  O = order(A)
  n = degree(O)

  if is_zero(A)
    A.basis_matrix = zero_matrix(base_ring(O), n, n)
    return nothing
  end

  if has_princ_gen(A)
    A.basis_matrix = _reduce_row_module!(representation_matrix(A.princ_gen); reduction = HNFRedTrait())
    return nothing
  end

  @hassert :GenOrd 1 has_2_elem(A)

  if has_2_elem_normal(A)
    # minimum is cheap here, so we can build the basis via a modular hnf.
    m = minimum(A; copy = false)
    # V is [ m*I ; M_{gen_two mod m} ],  where M_x is the representation matrix of x
    V = vcat(scalar_matrix(base_ring(O), n, m), representation_matrix(mod(A.gen_two, m)))
    A.basis_matrix = _reduce_row_module!(V; reduction = HNFRedTrait(), modulus = m)
    return nothing
  end

  V = vcat(representation_matrix(O(A.gen_one)), representation_matrix(A.gen_two))
  A.basis_matrix = _reduce_row_module!(V; reduction = HNFRedTrait())
  return nothing
end

################################################################################
#
#  Basis matrix inverse
#
################################################################################

@doc raw"""
    has_basis_mat_inv(A::GenOrdIdl) -> Bool

Return whether $A$ knows its inverse basis matrix.
"""
has_basis_mat_inv(A::GenOrdIdl) = isdefined(A, :basis_matrix_inv_num)

@doc raw"""
    basis_mat_inv(A::GenOrdIdl) -> MatElem

Return the inverse of the basis matrix of $A$.
"""
function Hecke.basis_mat_inv(A::GenOrdIdl{S, T}; copy::Bool = false) where {S, T}
  M, d = _basis_matrix_inv_pair(A)

  k = base_field(field(order(A)))::base_field_type(S)
  return divexact(change_base_ring(k, M), k(d))
end

function _assure_has_basis_matrix_inv(A::GenOrdIdl{S, T}) where {S, T}
  if !isdefined(A, :basis_matrix_inv_num)
    K = base_field(field(order(A)))::base_field_type(S)
    A.basis_matrix_inv_num, A.basis_matrix_inv_den = _inv_pair(basis_matrix(A; copy = false), K)
  end
  return nothing
end

function _basis_matrix_inv_pair(A::GenOrdIdl{S, T}) where {S, T}
  _assure_has_basis_matrix_inv(A)
  return (A.basis_matrix_inv_num::dense_matrix_type(elem_type(T)), A.basis_matrix_inv_den::elem_type(T))
end

###########################################################################################
#
#   Misc
#
###########################################################################################

(O::GenOrd)(p::PolyRingElem) = O(O.F(p))
Hecke.is_commutative(O::GenOrd) = true

Nemo.elem_type(::Type{GenOrd}) = GenOrdElem

function Hecke.hnf(x::T, shape::Symbol =:upperright) where {T <: MatElem}
  if shape == :lowerleft
    h = hnf(reverse_cols(x))
    reverse_cols!(h)
    reverse_rows!(h)
    return h::T
  end
  return hnf(x)::T
end

################################################################################
#
#  Multiplication
#
################################################################################

function _mul_gen(a::GenOrdIdl{S, T}, b::GenOrdIdl{S, T}) where {S, T}
  O = order(a)
  ideal(O, _mul_impl_matrix_stack(HNFRedTrait(), a, b); M_in_hnf = true)
end

function _mul_maximal(a::GenOrdIdl{S, T}, b::GenOrdIdl{S, T}) where {S, T}
  if has_2_elem_normal(a) && has_2_elem_normal(b)
    return _mul_2elem_normal(a, b)
  end

  return _mul_gen(a, b)
end

# Renormalize to the joint modulus:
# At primes of a1, the coprime part f is a unit.
# At the new (added) primes q | m, we have q | f and a1 is a unit.
# We compute a new second generator beta = f*alpha + a1^2 for the modulus m.
# For prime p of a1: v_p(f*alpha + a1^2) = v_p(alpha) = v_p(A) [this is why a1^2, not a1]
# For an added prime q: v_q(f*alpha + a1^2) = v_q(a1^2) = 0 = v_q(A)
function _renormalize_gen_two(alpha::GenOrdElem, a1::RingElem, m::RingElem)
  _, f = ppio(m, a1)
  is_unit(f) && return alpha
  return f*alpha + parent(alpha)(a1^2)
end

# Reduce gen_two using known minimum: for <m, alpha> we want to reduce alpha.
# Simple-minded <m, alpha mod m> represent same ideal, but might be not normal.
# Instead we compute <m, alpha mod m^2>.
# By normality: v_P(alpha) = v_P(A) <= v_P(m) for P | m
# For any delta in m^2*O: v_P(delta) >= 2*v_P(m) > v_P(m) >= v_P(alpha)
#   giving v_P(alpha + delta) = v_P(alpha) for P | m
# For delta in m*O, we have only v_P(delta) >= v_P(m) >= v_P(alpha);
#   when v_P(delta) = v_P(alpha), alpha + delta might cancel, giving
#   v_P(alpha + delta) > v_P(alpha) = v_P(A), breaking normality
# NOTE: it is enough for m to be a multiple of the minimum, so for example
#   gen_one can be passed here (when we know we have a normal representation).
function _reduce_gen_two_2elem_normal(alpha::GenOrdElem, m::RingElem)
  return mod(alpha, m^2)
end

function _mul_2elem_normal(a::GenOrdIdl{S, T}, b::GenOrdIdl{S, T}) where {S, T}
  @hassert :GenOrd 1 has_2_elem_normal(a)
  @hassert :GenOrd 1 has_2_elem_normal(b)

  O = order(a)
  a1 = has_minimum(a) ? minimum(a; copy = false) : a.gen_one
  b1 = has_minimum(b) ? minimum(b; copy = false) : b.gen_one
  m = lcm(a1, b1)

  a2 = a.gen_two
  b2 = b.gen_two
  if a.gens_normal != b.gens_normal
    a2 = _renormalize_gen_two(a2, a1, m)
    b2 = _renormalize_gen_two(b2, b1, m)
  end

  # (a1, a2) and (b1, b2) are now m-normal over the shared base m
  g1 = _make_canonical_in(O, a1*b1)
  g2 = _reduce_gen_two_2elem_normal(a2*b2, g1)
  c = ideal(O, g1, g2)

  c.gens_normal = m
  c.norm = _make_canonical_in(O, norm(a; copy = false)*norm(b; copy = false))
  if has_minimum(a) && has_minimum(b) && is_unit(gcd(a1, b1))
    c.minimum = g1
  end

  @hassert :GenOrd 2 defines_2_normal(c)
  return c
end

function Base.:(*)(a::GenOrdIdl{S, T}, b::GenOrdIdl{S, T}) where {S, T}
  @req order(a) === order(b) "Ideals must have same order"

  is_zero(a) && return a
  is_zero(b) && return b
  is_one(a)  && return b
  is_one(b)  && return a

  O = order(a)
  return is_maximal_known_and_maximal(O) ? _mul_maximal(a, b) : _mul_gen(a, b)
end

################################################################################
#
#  Binary Operations
#
################################################################################

function Base.:(+)(a::GenOrdIdl{S, T}, b::GenOrdIdl{S, T}) where {S, T}
  @req order(a) === order(b) "Ideals must have same order"

  is_zero(a) && return b
  is_zero(b) && return a
  is_one(a)  && return a
  is_one(b)  && return b

  O = order(a)

  g = gcd(minimum(a; copy = false), minimum(b; copy = false))
  V = vcat(basis_matrix(a; copy = false), basis_matrix(b; copy = false))
  V = hnf_modular_eldiv_left!(V, g)
  return ideal(O, V; M_in_hnf = true)
end

function Base.:(==)(a::GenOrdIdl{S, T}, b::GenOrdIdl{S, T}) where {S, T}
  order(a) === order(b) || return false
  return basis_matrix(a; copy = false) == basis_matrix(b; copy = false)
end
function Base.isequal(a::GenOrdIdl{S, T}, b::GenOrdIdl{S, T}) where {S, T}
  return a == b
end

@doc raw"""
    intersect(x::GenOrdIdl, y::GenOrdIdl) -> GenOrdIdl

Returns $x \cap y$.
"""
function Base.intersect(a::GenOrdIdl{S, T}, b::GenOrdIdl{S, T}) where {S, T}
  @req order(a) === order(b) "Ideals must have same order"

  is_zero(a) && return a
  is_zero(b) && return b
  is_one(a)  && return b
  is_one(b)  && return a

  # [A A ; 0 B] lower left HNF gives intersection in the top left block
  O = order(a)
  n = degree(O)

  g = lcm(minimum(a; copy = false), minimum(b; copy = false))
  Ma = basis_matrix(a; copy = false)
  Mb = basis_matrix(b; copy = false)
  V = vcat(hcat(Ma, Ma), hcat(zero_matrix(base_ring(O), n, n), Mb))
  H = sub(hnf_modular_eldiv_left!(V, g), 1:n, 1:n)
  return ideal(O, H; M_in_hnf = true)
end

################################################################################
#
#  Powering
#
################################################################################

function Base.:(^)(A::GenOrdIdl, e::Int)
  O = order(A)
  if e == 0
    return ideal(O, one(O))
  elseif e == 1
    return A
  elseif e < 0
    return inv(A)^(-e)
  end
  return Base.power_by_squaring(A, e)
end


################################################################################
#
#  Ad hoc multiplication
#
################################################################################

# Multiplying an integral ideal by a *base ring* scalar is equivalent to
#   scaling the ideal basis matrix.
# Internal helper for base-ring scalar case
function _ideal_by_scaling_matrix(c, I::GenOrdIdl)
  O = order(I)
  # we must ensure canonical form, to keep HNF canonical
  c = _make_canonical_in(O, c)

  is_zero(c) && return ideal(O, c)
  is_one(c) && return I
  return ideal(O, c * basis_matrix(I; copy = false); M_in_hnf = true)
end

# This is the check for "scalar is in the base ring"
# Since x is GenOrdElem, it is integral, so we need to check if it is in the base field
function _is_in_base_field(x::GenOrdElem)
  a = data(x)
  for i in 1:degree(parent(a)) - 1
    is_zero(coeff(a, i)) || return false
  end
  return true
end

function Base.:*(x::GenOrdElem, O::GenOrd)
  return ideal(O, x)
end

function Base.:*(x::GenOrdElem, I::GenOrdIdl{S, T}) where {S, T}
  O = order(I) # note that this has concrete type for type inference
  @req parent(x) === O "Element and ideal must belong to the same order"

  if _is_in_base_field(x)
    c, den = integral_split(coeff(data(x), 0), base_ring(O))
    @assert is_one(den)
    return _ideal_by_scaling_matrix(c, I)
  end

  return ideal(O, x) * I
end

Base.:*(x::GenOrdIdl, y::GenOrdElem) = y * x

# For A = <m, alpha> with m = minimum(A) in m-normal two-element representation
#   A^{-1} = O + beta*O, with beta = d_c * alpha^{-1}, d_c = part of denom(alpha^{-1}) coprime to m.
# We compute this ideal as <d_m, gamma>/d_m, with
#   gamma = numerator(alpha^{-1}, O) = d*alpha^{-1}; d = denom(alpha^{-1})
#   d_m = part of denom(alpha^{-1}) supported at m.
# We then have <d_m, gamma> = d_m*A^{-1} normal
function _inv_2elem_normal(O::GenOrd, A::GenOrdIdl)
  @hassert :GenOrd 1 has_2_elem_normal(A)

  m = minimum(A; copy = false)
  is_unit(m) && return fractional_ideal(A)

  gamma, d = integral_split(inv(data(A.gen_two)), O)
  d_m = _make_canonical_in(O, ppio(d, m)[1])

  Ai = ideal(O, d_m, _reduce_gen_two_2elem_normal(gamma, d_m))
  Ai.gens_normal = A.gens_normal
  Ai.norm = _make_canonical_in(O, divexact(d_m^degree(O), norm(A; copy = false)))
  @hassert :GenOrd 2 defines_2_normal(Ai)
  return fractional_ideal(Ai, d_m)
end

function inv(I::GenOrdIdl)
  @req !is_zero(I) "Ideal must be nonzero"

  O = order(I)

  if is_maximal_known_and_maximal(O) && has_2_elem_normal(I)
    B = _inv_2elem_normal(O, I)
    return B
  end

  # (O : A) is inverse iff A is coprime to the conductor (otherwise A is not invertible)
  return _inv_impl(HNFRedTrait(), O, I)
end

################################################################################
#
#  Exact Division
#
################################################################################


function Hecke.divexact(A::GenOrdIdl, b::RingElem)
  is_zero(A) && return A

  O = order(A)
  b = _make_canonical_in(O, b)
  is_unit(b) && return A

  bm = divexact(basis_matrix(A; copy = false), b)
  B = ideal(O, bm; M_in_hnf = true)

  if has_princ_gen(A)
    # Coerce the base-ring scalar b through the base field before embedding it
    #   into O.F before dividing.
    bF = O.F(base_field(O.F)(b))
    B.princ_gen = O(divexact(O.F(A.princ_gen), bF))
  end

  return B
end


function has_minimum(A::GenOrdIdl)
  return isdefined(A, :minimum)
end

function Hecke.minimum(A::GenOrdIdl; copy::Bool = true)
  assure_has_minimum(A)
  if copy
    return deepcopy(A.minimum)::elem_type(base_ring(order(A)))
  else
    return A.minimum::elem_type(base_ring(order(A)))
  end
end

# for the principal ideal <alpha>: m in alpha*O <=> m/alpha in O.
# smallest such m (the minimum) is denominator of alpha^-1
function _minimum_principal(O::GenOrd, alpha::GenOrdElem)
  return _make_canonical_in(O, denominator(inv(data(alpha)), O))
end

# for <p, alpha> normal, the minimum is gcd(p, min(<alpha>))
function _minimum_2elem_normal(O::GenOrd, gen_one::RingElem, gen_two::GenOrdElem)
  return _make_canonical_in(O, gcd(gen_one, _minimum_principal(O, gen_two)))
end

function assure_has_minimum(A::GenOrdIdl)
  if has_minimum(A)
    return nothing
  end

  O = order(A)

  if has_2_elem_normal(A)
    A.minimum = _minimum_2elem_normal(O, A.gen_one, A.gen_two)
  elseif isone(basis(O; copy = false)[1])
    A.minimum = deepcopy(basis_matrix(A; copy = false)[1, 1])
  else
    M = basis_matrix(A; copy = false)
    d = prod([M[i, i] for i = 1:nrows(M)])
    v = transpose(matrix(map(base_ring(O), coordinates(O(d)))))
    fl, s = can_solve_with_solution(M, v, side = :left)
    @assert fl
    den = denominator(s[1]//d)
    for i = 2:ncols(s)
      den = lcm(den, denominator(s[i]//d))
    end

    A.minimum = _make_canonical_in(O, den)
  end

  return nothing
end

################################################################################
#
#  Norm
#
################################################################################

@doc raw"""
    has_norm(A::GenOrdIdl) -> Bool

Return whether $A$ knows its norm.
"""
function has_norm(A::GenOrdIdl)
  return isdefined(A, :norm)
end

# for <p, alpha> normal, the norm is gcd(p^n, Norm(alpha))
function _norm_2elem_normal(O::GenOrd, gen_one::RingElem, gen_two::GenOrdElem)
  return _make_canonical_in(O, gcd(gen_one^degree(O), norm(gen_two)))
end

function assure_has_norm(A::GenOrdIdl)
  if has_norm(A)
    return nothing
  end

  O = order(A)

  if has_2_elem_normal(A)
    A.norm = _norm_2elem_normal(O, A.gen_one, A.gen_two)
  else
    A.norm = _make_canonical_in(O, det(basis_matrix(A; copy = false)))
  end
  return nothing
end

@doc raw"""
    norm(A::GenOrdIdl) -> RingElem

Return the norm of $A$, that is, the cardinality of $\mathcal O/A$, where
$\mathcal O$ is the order of $A$.
"""
function Hecke.norm(A::GenOrdIdl; copy::Bool = true)
  assure_has_norm(A)
  return (copy ? deepcopy(A.norm) : A.norm)::elem_type(base_ring(order(A)))
end

################################################################################
#
#  Numerator and Denominator
#
################################################################################

function Hecke.numerator(a::Generic.AbsSimpleFunctionFieldElem, O::GenOrd)
  return integral_split(a,O)[1]
end

function Hecke.denominator(a::Generic.AbsSimpleFunctionFieldElem, O::GenOrd)
  return integral_split(a,O)[2]
end

################################################################################
#
#  Principal Generator
#
################################################################################

@doc raw"""
    has_princ_gen(A::GenOrdIdl) -> Bool

Returns whether $A$ knows if it is generated by one element.
"""
function has_princ_gen(A::GenOrdIdl)
  return isdefined(A, :princ_gen)
end

################################################################################
#
#  Reduction of element modulo ideal
#
################################################################################

@doc raw"""
    mod(x::GenOrdElem, y::GenOrdIdl) -> GenOrdElem

Return the unique element $z$ with $x \equiv z \bmod y$ obtained by reducing
the coordinate vector of $x$ against the lower-left HNF basis matrix of $y$.
"""
function Hecke.mod(x::GenOrdElem, y::GenOrdIdl)
  parent(x) !== order(y) && error("GenOrds of element and ideal must be equal")
  # this function assumes that HNF is lower left
  # !!! This must be changed as soon as HNF has a different shape

  O = order(y)
  d = degree(O)
  a = base_ring(O).(coordinates(x))

  c = basis_matrix(y)
  # reduce starting from the last coordinate: row i only affects columns 1:i,
  #   so going from d down to 1 finalizes each coordinate exactly once
  for i in d:-1:1
    r = mod(a[i], c[i,i])
    # for ZZRingElem, div/mod round differently (div truncates, mod floors),
    #   so t must come from mod, not div, to get the canonical representative
    if r != a[i]
      t = divexact(a[i] - r, c[i,i])
      for j in 1:(i - 1)
        a[j] = a[j] - t*c[i,j]
      end
      a[i] = r
    end
  end
  z = O([a[i] for i in 1:length(a)])
  return z
end

################################################################################
#
#  Residue field
#
################################################################################

function Hecke.residue_field(R::fpPolyRing, p::fpPolyRingElem)
  K, _ = finite_field(p,"o")
  return K, MapFromFunc(R, K, x->K(x), y->R(y))
end

function Hecke.residue_field(R::FqPolyRing, p::FqPolyRingElem)
  return Nemo._residue_field(p, absolute = false)
end

################################################################################
#
#  Factorization
#
################################################################################

function Hecke.index(O::GenOrd)
  return is_equation_order(O) ? O.R(1) : O.R(det(basis_matrix_inverse(O)))
end

function prime_dec_nonindex(O::GenOrd{S, T}, p::RingElem, degree_limit::Int = 0, lower_limit::Int = 0) where {S, T}
  @req parent(p) === base_ring(O) "p must come from the base ring of O"

  F = field(O)
  B = base_field(F)
  a = gen(F)

  K, mK = residue_field(base_ring(O), p)

  fmodp = map_coefficients(defining_polynomial(O.F); cached = false) do c
    num, den = integral_split(c, base_ring(O))
    mK(num) // mK(den)
  end
  fact = factor(fmodp)

  result = Vector{Tuple{GenOrdIdl{S, T}, Int}}(undef, length(fact))
  for (i, (fac, e)) in enumerate(fact)
    f = degree(fac)
    facnew = map_coefficients(y -> B(preimage(mK, y)), fac, cached = false)

    # facnew(a) is integral at p, but a itself need not be globally integral,
    #   since we only require the defining polynomial to be locally integral at p.
    # To bring it back into O, scale by the denominator (which is coprime to p);
    #   this is equivalent to taking the numerator directly.
    b = numerator(facnew(a), O)

    # We want a P-normal two-element presentation, i.e. v_P(b) = 1.
    # Since we are in the case of p not dividing the index, we have a good candidate b = g(a).
    #
    # v_P(<p,b>) = min[v_P(p), v_P(b)] = 1.
    # Ramified case   (e > 1): v_P(p) = e > 1, so v_P(b) = 1 is forced.
    # Unramified case (e = 1): v_P(b) can exceed 1, in which case
    #   v_P(b + p) = min(v_P(b), 1) = 1
    # For other primes Q over p, v_Q(b) > 0 would give v_Q(<p, b>) > 0,
    #   giving <p,b> subset of Q, contradicting <p, b> = P.
    #
    # In the unramified case we need to check if v_P(b) == 1.
    # One possibility is to check if p*N(P) = p^{f+1} divides N(b)
    #   and if it doesn't, we must have v_P(b) == 1.
    # Unlike the number field case, b can be zero (single inert prime over p),
    #   which is also covered by adding p.
    if e == 1 && (is_zero(b) || divides(norm(b), p^(f + 1))[1])
      b = b + O(p)
    end

    I = ideal(O, p, b)
    I.gens_normal = p
    I.is_prime = 1
    I.splitting_type = e, f
    I.norm = p^f
    I.minimum = p

    # inert prime
    if f == degree(O)
      I.princ_gen = O(p)
      I.is_principal = 1
    end

    result[i] = (I,e)
  end
  return result
end

function Hecke.valuation(A::GenOrdIdl{S, T}, p::GenOrdIdl{S, T}) where {S, T}
  @req !is_zero(A) "A is zero"

  O = order(A)
  e = 0
  if has_2_elem_normal(p)
    beta = Hecke.numerator(inv(O.F(p.gen_two)), O)
    newA = fractional_ideal(beta*A, p.gen_one)
    while is_integral(newA)
      e += 1
      newA = fractional_ideal(numerator(beta*newA; copy = false), p.gen_one)
    end
  else
    newA = Hecke.colon(A,p)
    while is_integral(newA)
      e+=1
      newA = Hecke.colon(newA,fractional_ideal(p))
    end
  end
  return e
end


function Hecke.factor(A::GenOrdIdl{S, T}) where {S, T}
  O = A.order
  N = norm(A)
  factors = factor(N)
  primes = Dict{GenOrdIdl{S, T},Int}()
  for (f,e) in factors
    for (p,r) in prime_decomposition(O,f)
      p_val = valuation(A, p)
      if p_val != 0
        primes[p] = p_val
      end
    end
  end
  return primes
end

# For the Dedekind-Kummer criterion we need to consider the local (at p) defining polynomial f.
# In general, we do not need the defining polynomial to be monic;
#   we can make it monic in the base field and then consider its localization.
# Currently, we demand that f is monic "globally" (that is, leading coefficient is 1),
#   so it is enough to check the valuations of the denominators.

# The local version of is_defining_polynomial_nice:
#   checks whether the polynomial is monic and the coefficient valuations are non-negative.
function _is_defining_polynomial_nice_at(O::GenOrd, p::RingElem)
  @req parent(p) === base_ring(O) "p must lie in the coefficient ring of O"
  f = defining_polynomial(field(O))
  is_one(leading_coefficient(f)) || return false

  R = base_ring(O)
  for c in coefficients(f)
    divides(denominator(c, R), p)[1] && return false
  end

  return true
end

function is_index_divisor(O::GenOrd, p::RingElem)
  @req parent(p) === base_ring(O) "p must lie in the coefficient ring of O"
  is_equation_order(O) && return false

  num, den = integral_split(det(basis_matrix_inverse(O)), base_ring(O))
  # if p divides the numerator, it divides the index;
  # if p divides the denominator, the order is not maximal at p (cannot use Dedekind-Kummer)
  return divides(num, p)[1] || divides(den, p)[1]
end

function prime_decomposition(O::GenOrd{S, T}, p::RingElem, degree_limit::Int = degree(O), lower_limit::Int = 0; cached::Bool = true) where {S, T}
  if _is_defining_polynomial_nice_at(O, p) && !is_index_divisor(O, p)
    return prime_dec_nonindex(O, p, degree_limit, lower_limit)
  else
    return prime_dec_gen(O, p, degree_limit, lower_limit)
  end
end

function prime_dec_gen(O::GenOrd{S, T}, p::RingElem, degree_limit::Int = degree(O), lower_limit::Int = 0) where {S, T}
  Ip = pradical(O, p)
  lp = _decomposition(O, ideal(O, p), Ip, p)
  #=z = Tuple{ideal_type(O), Int}[]
  for (Q, e) in lp
    if degree(Q) <= degree_limit && degree(Q) >= lower_limit
      push!(z, (Q, e))
    end
  end
  return z
  =#
  return lp
end

function residue_field(R::PolyRing{QQBarFieldElem}, p::PolyRingElem{QQBarFieldElem})
  @assert degree(p) == 1
  @assert is_monic(p)
  c = -coeff(p, 0)
  K = base_ring(R)
  f = MapFromFunc(R, K, q -> q(c), x -> R(x))
  return K, f
end

function Hecke.pradical(O::GenOrd, p::RingElem)
  R, mR = residue_field(parent(p), p)

#  @assert characteristic(F) == 0 || (isfinite(F) && characteristic(F) > degree(O))
  if characteristic(R) == 0 || characteristic(R) > degree(O)
    @vprintln :GenOrd 1 "using trace-radical for $p"
    rad = radical_basis_trace
  elseif isa(R, Generic.RationalFunctionField)
    @vprintln :GenOrd 1 "non-perfect case for radical for $p"
    rad = radical_basis_power_non_perfect
  else
    @vprintln :GenOrd 1 "using radical-by-power for $p"
    rad = radical_basis_power
  end
  return ideal(O, rad(O,p); M_in_hnf = true)
end

function _basis_uniformizer(P::GenOrdIdl, p::RingElem, f::Int)
  # We have one prime above p.
  # If we are in maximal (at p) order, at least one element of the basis
  #   must have valuation exactly 1 (otherwise all of them are in P^2).
  q = p^(f + 1)
  for b in basis(P)
    divides(norm(b), q)[1] || return b
  end

  return nothing # non-maximal at p: no certified uniformizer
end

function _idempotent_uniformizer(P::GenOrdIdl, p::RingElem, f::Int, idempotent::GenOrdElem)
  O = order(P)

  # From structure algebra decomposition, we have idempotent e_j such that
  #   e_j = 1 mod P_j and e_j = 0 mod P_i for i != j
  # We have v_P(u) >= 1 and v_Q(u) = 0 for Q != P above p
  u = one(O) - idempotent

  q = p^(f + 1)
  divides(norm(u), q)[1] || return u

  # v_P(u) >= 2. Try shifting by idempotent without changing the valuation
  #   at other primes Q != P above p
  # If we have basis element b of valuation 1 we have v_P(u + b*idempotent) = 1
  #   and the valuation at other primes stays 0 (due to idempotent)
  # As above: such a basis element is guaranteed in p-maximal order
  #   but if not found, then we just won't have gen_two set
  for b in basis(P)
    u2 = u + idempotent*b
    divides(norm(u2), q)[1] || return u2
  end

  return nothing
end

function _decomposition(O::GenOrd{S, T}, I::GenOrdIdl{S, T}, Ip::GenOrdIdl{S, T}, p::RingElem) where {S, T}
  #I is an ideal lying over p
  #Ip is the p-radical
  Ip1 = Ip + I
  A, OtoA = StructureConstantAlgebra(O, Ip1, p)

  AtoO = pseudo_inv(OtoA)
  ideals, AA = _from_algs_to_ideals(A, OtoA, AtoO, Ip1, p)

  pcount = length(ideals)

  # check if we have inert prime: we then have principal ideal
  if pcount == 1 && ideals[1][1].splitting_type[2] == degree(O)
    P = ideals[1][1]
    P.splitting_type = 1, degree(O)

    P.gen_one = p
    P.gen_two = O(p)
    P.gens_normal = p
    P.princ_gen = O(p)
    P.is_principal = 1

    ideals[1] = (P, 1)
    return ideals
  end

  for i in 1:pcount
    P = ideals[i][1]
    f = P.splitting_type[2]

    # find uniformizer (gen_two)
    P_uni = if pcount == 1
      _basis_uniformizer(P, p, f)
    else
      idem  = AtoO(AA[i][2](one(AA[i][1])))
      _idempotent_uniformizer(P, p, f, idem)
    end

    # if we have found uniformizer: set normal representation
    if P_uni !== nothing
      P.gen_one = p
      P.gen_two = P_uni
      P.gens_normal = p
    end

    e = valuation(ideal(O, p), P)
    P.splitting_type = e, f
    ideals[i] = (P, e)
  end

  return ideals
end

function StructureConstantAlgebra(O::GenOrd, I::GenOrdIdl, p::RingElem)
  FQ, phi = residue_field(base_ring(O), p)
  StructureConstantAlgebra(O, I, p, phi)
end

function StructureConstantAlgebra(O::GenOrd, I::GenOrdIdl, p::RingElem, phi)
  @assert order(I) === O

  n = degree(O)
  bmatI = basis_matrix(I)

  basis_elts = Vector{Int}()
  for i = 1:n
    if is_coprime(bmatI[i, i], p)
      continue
    end

    push!(basis_elts, i)
  end

  r = length(basis_elts)
  FQ = codomain(phi)

  if r == 0
    A = zero_algebra(FQ)

    local _image_zero

    let A = A
      function _image_zero(a::GenOrdElem)
        return A()
      end
    end

    local _preimage_zero

    let O = O
      function _preimage_zero(a::AssociativeAlgebraElem)
        return O()
      end
    end

    OtoA = Hecke.AbsOrdToAlgAssMor{typeof(O), elem_type(FQ)}(O, A, _image_zero, _preimage_zero)
    return A, OtoA
  end

  BO = basis(O)
  mult_table = Array{elem_type(FQ), 3}(undef, r, r, r)
  for i = 1:r
    M = representation_matrix(BO[basis_elts[i]])
    #TODO: write version of reduce rows mod hnf
    if r != degree(O)
      M = reduce_rows_mod_hnf!(M, bmatI, basis_elts)
    end
    for j = 1:r
      for k = 1:r
        mult_table[i, j, k] = phi(M[basis_elts[j], basis_elts[k]])
      end
    end
  end

  if isone(BO[1])
    one = [zero(FQ) for _ in 1:r]
    one[1] = FQ(1)
    A = StructureConstantAlgebra(FQ, mult_table, one)
  else
    A = StructureConstantAlgebra(FQ, mult_table)
  end
  if is_commutative(O)
    A.is_commutative = 1
  end

  local _image

  let I = I, A = A, basis_elts = basis_elts, FQ = FQ
    function _image(a::GenOrdElem)
      c = coordinates(mod(a, I))
      return A([phi(O.R(c[i])) for i in basis_elts ])
    end
  end

  local _preimage

  let BO = BO, basis_elts = basis_elts, r = r
    function _preimage(a::AssociativeAlgebraElem)
      ca = coefficients(a)
      return sum(preimage(phi, ca[i]) * BO[basis_elts[i]] for i in 1:length(ca))
    end
  end

  OtoA = GenOrdToAlgAssMor{typeof(O), elem_type(FQ)}(O, A, _image, _preimage)

  return A, OtoA
end

# Reduces the rows of M in `rows` modulo N in place.
# Assumes that N is in lowerleft HNF.
function reduce_rows_mod_hnf!(M::MatElem, N::MatElem, rows::Vector{Int})
  for i in rows
    for j = ncols(M):-1:1
      if iszero(M[i, j])
        continue
      end

      t = div(M[i, j], N[j, j])
      for k = 1:j
        M[i, k] = M[i, k] - t*N[j, k]
      end
    end
  end
  return M
end

################################################################################
#
#   Degree and ramification index
#
################################################################################

@doc raw"""
    degree(P::GenOrdIdl) -> Int
    inertia_degree(P::GenOrdIdl) -> Int

The inertia degree of the prime-ideal $P$.
"""
function degree(P::GenOrdIdl)
  @assert is_prime(P)
  return P.splitting_type[2]
end

inertia_degree(P::GenOrdIdl) = degree(P)

@doc raw"""
    ramification_index(P::GenOrdIdl) -> Int

The ramification index of the prime-ideal $P$.
"""
function ramification_index(P::GenOrdIdl)
  @assert is_prime(P)
  return P.splitting_type[1]
end


################################################################################
#
#  Primality testing
#
################################################################################

@doc raw"""
    is_prime_known(A::GenOrdIdl) -> Bool

Returns whether $A$ knows if it is prime.
"""
function is_prime_known(A::GenOrdIdl)
  return A.is_prime != 0
end

@doc raw"""
    is_prime(A::GenOrdIdl) -> Bool

Returns whether $A$ is a prime ideal.
"""
function is_prime(A::GenOrdIdl)
  if is_prime_known(A)
    return A.is_prime == 1
  elseif minimum(A) == 0
    A.is_prime = 1
    return true
  end

  lp = factor(A)
  for (P, e) in lp
    if norm(A) != norm(P)
      continue
    end

    # from factorization we know already that A is in P
    # TODO: for non-maximal orders we need to check both generators
    # TODO: though most of our code around primes assumes maximal order
    PinA = if has_2_elem(P)
      P.gen_two in A
    else
      A == P
    end

    if PinA
      A.is_prime = 1
      A.splitting_type = P.splitting_type
      return true
    end
  end
  A.is_prime = 2
  return false
end

################################################################################
#
#  Inclusion of elements in ideals
#
################################################################################

@doc raw"""
    in(x::GenOrdElem, y::GenOrdIdl)

Returns whether $x$ is contained in $y$.
"""
function in(x::GenOrdElem, y::GenOrdIdl)
  @req parent(x) === order(y) "Both element and ideal must come from the same order"
  return containment_by_matrices(x, y)
end

function containment_by_matrices(x::GenOrdElem, y::GenOrdIdl)
  A, den = _basis_matrix_inv_pair(y)
  kx = base_ring(order(y))
  R = residue_ring(kx, den; cached = false)[1]
  M = map_entries(R, A)
  coords = coordinates(x)
  v = matrix(R, 1, degree(parent(x)), coords)
  #mul!(v, v, M) This didn't work
  v = v*M
  return iszero(v)
end

###############################################################################
#
#  Decomposition type using polygons
#
###############################################################################

function _from_algs_to_ideals(A::StructureConstantAlgebra{T}, OtoA::Map, AtoO::Map, Ip1::GenOrdIdl, p::RingElem) where {T}

  O = order(Ip1)
  n = degree(O)
  R = O.R
  @vprintln :GenOrd 1 "Splitting the algebra"
  AA = Hecke.decompose(A)
  @vprintln :GenOrd 1 "Done"
  ideals = Vector{Tuple{typeof(Ip1), Int}}(undef, length(AA))
  N = basis_matrix(Ip1; copy = false)
  list_bases = Vector{Vector{Vector{elem_type(R)}}}(undef, length(AA))
  for i = 1:length(AA)
    l = Vector{Vector{elem_type(R)}}(undef, dim(AA[i][1]))
    for j = 1:length(l)
      v = map(O.R,coordinates(AtoO(AA[i][2](AA[i][1][j]))))
      l[j] = [v[o] for o in 1:length(v)]
    end
    list_bases[i] = l
  end
  for i = 1:length(AA)
    B = AA[i][1]
    BtoA = AA[i][2]
    #we need the kernel of the projection map from A to B.
    #This is given by the basis of all the other components.
    f = dim(B)
    N1 = vcat(N, zero_matrix(R, dim(A) - f, n))
    t = 1
    for j = 1:length(AA)
      if j == i
        continue
      end
      for s = 1:length(list_bases[j])
        b = list_bases[j][s]
        for j = 1:degree(O)
          N1[n + t, j] = b[j]
        end
        t += 1
      end
    end

    P = ideal(O, hnf(N1, :lowerleft); M_in_hnf = true)
    P.minimum = p
    P.norm = p^f
    P.splitting_type = (0, f)
    P.is_prime = 1
    fromOtosimplealgebra = compose(OtoA, pseudo_inv(BtoA))
    #compute_residue_field_data!(P, fromOtosimplealgebra)
    ideals[i] = (P, 0)
  end
  return ideals, AA
end


################################################################################
#
#  GenOrdToAlgAssMor type
#
################################################################################

mutable struct GenOrdToAlgAssMor{S, T} <: Map{S, StructureConstantAlgebra{T}, Hecke.HeckeMap, Any}#GenOrdToAlgAssMor}
  header::Hecke.MapHeader

  function GenOrdToAlgAssMor{S, T}(O::S, A::StructureConstantAlgebra{T}, _image::Function, _preimage::Function) where {S <: GenOrd, T}
    z = new{S, T}()
    z.header = Hecke.MapHeader(O, A, _image, _preimage)
    return z
  end
end

function GenOrdToAlgAssMor(O::GenOrd, A::StructureConstantAlgebra{T}, _image, _preimage) where {T}
  return GenOrdToAlgAssMor{typeof(O), T}(O, A, _image, _preimage)
end

################################################################################
#
#  Misc.
#
################################################################################

function Hecke.characteristic(R::EuclideanRingResidueField{<:Hecke.GenOrdElem{<:Generic.AbsSimpleFunctionFieldElem}})
  return characteristic(function_field(base_ring(R)))
end

mutable struct GenOrdToFqField{S, T} <: Map{S, T, Hecke.HeckeMap, Any}#GenOrdToFqField}
  header::Hecke.MapHeader

  function GenOrdToFqField{S, T}(O::S, A::T, _image::Function, _preimage::Function) where {S <: GenOrd, T}
    z = new{S, T}()
    z.header = Hecke.MapHeader(O, A, _image, _preimage)
    return z
  end
end

function Nemo._residue_field(f::PolyRingElem{<:NumFieldElem})
  Kt = parent(f)
  L, b = number_field(f, "a"; cached = false)
  return L, MapFromFunc(Kt, L, x -> L(x), y -> Kt(y))
end

function residue_field(O::GenOrd, P::GenOrdIdl, check::Bool = true)
  a, g, b, phi = get_residue_field_data(P)::Tuple{elem_type(O),
                                                  poly_type(base_ring(O)),
                                                  Vector{dense_matrix_type(base_ring(O))},
                                                  Any} # not optimal
  gg = map_coefficients(phi, g)
  bb = map_entries.(phi, b)
  K = base_ring(parent(gg))
  F, KtoF = Nemo._residue_field(gg)
  d = degree(O)
  imgofbas = [KtoF(parent(gg)(bb[i][1, :])) for i in 1:d]
  powersofa = powers(a, degree(g))

  _image = function(x::GenOrdElem)
    @assert parent(x) === O
    c = base_ring(O).(coordinates(x))
    return sum(phi(c[i]) * imgofbas[i] for i in 1:d)
  end

  _preimage = function(x)
    @assert parent(x) === F
    return sum(preimage(phi, coeff(x, i - 1)) * powersofa[i] for i in 1:degree(g))
  end

  return F, GenOrdToFqField{typeof(O), typeof(F)}(O, F, _image, _preimage)
end
