# matrix algorithms specific to GenOrd

# Ideals are row modules
# They are represented by n x n matrix (with n equal to the order degree)
#   with basis vectors forming matrix rows.
# Zero ideals are treated explicitly, they are the only exception to full-column rank rule

###########################################################################################
#
#   HNF
#
###########################################################################################

# For integral ideals, the shape of this matrix is lower-left HNF.
# For all HNF functions we assume full column rank

# HNF of M assuming g is a multiple of the largest elementary divisor of the
#   row module L of M, that is g*R^m \subseteq L with m = ncols(M).
# Produces the *lower-left* HNF in place: the canonical basis occupies the
#   bottom m rows, lower triangular with reduced entries below each pivot.
# NOTE: AbstractAlgebra convention is upper-right
#   That's why we mark this with "_left" suffix
# This mirrors FLINT's fmpz_mat_hnf_modular_eldiv/nmod_mat_strong_echelon_form
#   (upper-right) by reflecting every index through the matrix center:
#   row r <-> n+1-r, col c <-> m+1-c.
#
# Phase 1 (echelon form modulo g):
#   step i clears column *above* the pivot.
# Phase 2 (strong echelon form) absorbs the implicit rows g*e_i:
#   the pivot becomes gcd(pivot, g), the column below it is reduced.
#   The leftover row (g/pivot)*row is merged into the diagonal positions up and to the left.
#   The lefover is the combination of the pivot row with g*e_i that survives modulo g.
# Phase 3 fills pivots that are still zero with g,
#   as those columns are generated by the implicit row alone.
function _hnf_modular_eldiv_left_generic!(M::MatElem{T}, g::T) where {T <: RingElem}
  # Mirrors FLINT's _n_stab (Storjohann's Stab):
  #   return t such that a + t*b is a unit modulo g
  function _stab(a::T, b::T, g::T)
    c = gcd(gcd(a, b), g)
    _, t = ppio(divexact(g, c), divexact(a, c))
    return t
  end

  # Mirrors FLINT's _n_unit:
  #   return a unit u modulo g with mod(u*a, g) == gcd(a, g)
  function _unit_mod(a::T, g::T)
    d, s, _ = gcdx(a, g)
    is_one(d) && return mod(s, g)
    l = divexact(g, d)
    t = _stab(s, l, g)
    return mod(s + t*l, g)
  end

  # In several places we need to store in the matrix the value of mod(t, g)
  #   where t is *temporary* variable used with mutating operations.
  # AbstractAlgebra mod for polynomials will return the same object t when
  #   its degree is less than degree of g.
  function _reduced_temp(a::T, g::T)
    r = mod(a, g)
    return r === a ? deepcopy(r) : r
  end

  # Replace the rows (a, b) with 2x2 unimodular transforms so that
  #   b[col] becomes 0 and a[col] becomes gcd(a[col], b[col]);
  #   columns above are reduced modulo g and columns below are left untouched.
  # With d = gcd(a[col], b[col]) = u*a[col] + v*b[col] the transform is
  #   (a; b) <- (u, v; -b[col]/d, a[col]/d) * (a; b),
  #   whose determinant is 1.
  function _combine!(a, b, col::Int, g::T)
    s1 = R(); s2 = R(); s3 = R()
    d, u, v = gcdx(a[col], b[col])
    u2 = -divexact(b[col], d)
    v2 =  divexact(a[col], d)
    for jc in 1:(col - 1)
      s1 = mul!(s1, u, a[jc]);  s1 = addmul!(s1, v, b[jc], s3)
      s2 = mul!(s2, u2, a[jc]); s2 = addmul!(s2, v2, b[jc], s3)
      a[jc] = _reduced_temp(s1, g)
      b[jc] = _reduced_temp(s2, g)
    end
    a[col] = d
    b[col] = zero(R)
    return nothing
  end

  @req !is_zero(g) "Modulus must be nonzero"
  n = nrows(M)
  m = ncols(M)
  @req n >= m "Matrix must have at least as many rows as columns"
  R = base_ring(M)

  # if g is unit, R^m == L and HNF is identity, sitting at the bottom m rows
  if is_unit(g)
    for i in 1:n, j in 1:m
      M[i, j] = (i == j + (n - m)) ? one(R) : zero(R)
    end
    return M
  end

  # canonicalize g
  g = divexact(g, canonical_unit(g))

  # reduce matrix modulo g
  for i in 1:n, j in 1:m
    M[i, j] = mod(M[i, j], g)
  end

  # scratch element for in-place arithmetic (_combine! keeps its own)
  t1 = R()

  # Phase 1: echelon form
  for i in 1:m
    pr = n + 1 - i   # pivot row
    pc = m + 1 - i   # pivot column

    # clear column pc above row pr by unimodular transforms (mod g)
    for kr in (pr - 1):-1:1
      # is already zero
      is_zero_entry(M, kr, pc) && continue

      # if not zero, check if pivot element is zero (update pivot)
      if is_zero_entry(M, pr, pc)
        swap_rows!(M, pr, kr)
        continue
      end

      # pivot M[pr, pc] is non-zero.
      fl, q = divides(M[kr, pc], M[pr, pc])
      if fl
        # pivot divides M[kr, pc]: do a plain row kr reduction
        q = neg!(q)
        for jc in 1:(pc - 1)
          t1 = mul!(t1, q, M[pr, jc])
          t1 = add!(t1, t1, M[kr, jc])
          M[kr, jc] = _reduced_temp(t1, g)
        end
        M[kr, pc] = zero(R)
      else
        # we need an unimodular transform for these two rows
        _combine!(view(M, pr, :), view(M, kr, :), pc, g)
      end
    end
  end

  # Phase 2: strong echelon form, absorbing the implicit rows g*e_pc
  extra_row = [zero(R) for _ in 1:m]
  for i in 1:m
    pr = n + 1 - i
    pc = m + 1 - i

    if !is_zero_entry(M, pr, pc)
      # make the pivot the canonical divisor gcd(M[pr, pc], g) of g
      u = _unit_mod(M[pr, pc], g)
      if !is_one(u)
        for jc in 1:pc
          t1 = mul!(t1, u, M[pr, jc])
          M[pr, jc] = _reduced_temp(t1, g)
        end
      end

      # reduce the entries of column pc below the pivot
      for kr in (pr + 1):n
        q = div(M[kr, pc], M[pr, pc])
        is_zero(q) && continue
        q = neg!(q)
        for jc in 1:pc
          t1 = mul!(t1, q, M[pr, jc])
          t1 = add!(t1, t1, M[kr, jc])
          M[kr, jc] = _reduced_temp(t1, g)
        end
      end

      # for a trivial pivot the leftover row vanishes modulo g
      is_one(M[pr, pc]) && continue

      c = divexact(g, M[pr, pc])
      for jc in 1:pc
        t1 = mul!(t1, c, M[pr, jc])
        extra_row[jc] = _reduced_temp(t1, g)
      end
    else
      # no pivot: the row content must still be pushed towards the diagonal
      for jc in 1:pc
        extra_row[jc] = deepcopy(M[pr, jc])
      end
    end

    # merge extra_row into the remaining diagonal positions;
    # each step zeroes extra_row at column dc, so whatever remains at the end lies in g*R^m
    for k in (i + 1):m
      dr = n + 1 - k
      dc = m + 1 - k
      is_zero(extra_row[dc]) && continue
      _combine!(view(M, dr, :), extra_row, dc, g)
    end
  end

  # Phase 3: pivots that are still zero are generated by g*e_pc alone
  for i in 1:m
    pr = n + 1 - i
    pc = m + 1 - i
    if is_zero_entry(M, pr, pc)
      M[pr, pc] = deepcopy(g)
    end
  end

  return M
end

function hnf_modular_eldiv_left!(M::MatElem{T}, g::T) where {T <: RingElem}
  return _hnf_modular_eldiv_left_generic!(M, g)
end

# Specialization for Q(x)
# Here the bottleneck is coefficient swell, not degree, so the modular HNF
#   brings no benefit by itself: its reduction only bounds the degree in x.
# Worse, the extra gcd/mod work actively amplifies the coefficient swell, so
#   until we find a way to fight that directly we fall back to Kannan-Bachem.
function hnf_modular_eldiv_left!(M::MatElem{QQPolyRingElem}, ::QQPolyRingElem)
  return _hnf_left!(M)
end

# Specialization for Z: use FLINT-backed functions
function hnf_modular_eldiv_left!(M::ZZMatrix, g::ZZRingElem)
  @req !is_zero(g) "Modulus must be nonzero"
  @req nrows(M) >= ncols(M) "Matrix must have at least as many rows as columns"

  return hnf_modular_eldiv!(M, abs(g), :lowerleft)
end

# Empirically hnf_minors and hnf_via_popov are better on "trivial" inputs,
#   but as the degree grows (e.g. larger powers of an ideal) hnf_kb becomes the clear winner.
function _hnf_left!(M::MatElem)
  reverse_cols!(M)
  AbstractAlgebra.hnf_kb!(M, similar(M, 0, 0))
  reverse_cols!(M)
  reverse_rows!(M)

  return M
end

function _hnf_left!(M::ZZMatrix)
  return _hnf!(M, :lowerleft)
end
