@attributes mutable struct GenOrd{S, T} <: Ring
  F::S
  R::T
  trans  #::dense_matrix_type(elem_type(base_field_type(S)))
  itrans #::dense_matrix_type(elem_type(base_field_type(S)))
  is_equation_order::Bool

  function GenOrd(R::AbstractAlgebra.Ring, F::AbstractAlgebra.Field, empty::Bool = false; check::Bool = true)
    #empty allows to create an Order that is none:
    # Z[x]/3x+1 is no order. This will be "fixed" by using any_order, but
    #the initial shell needs to be empty (illegal)
    r = new{typeof(F), typeof(R)}()
    r.F = F
    r.R = R
    r.is_equation_order = true

    Qt = base_field(F)
    if empty
      r.trans = identity_matrix(Qt, degree(F))
      r.itrans = identity_matrix(Qt, degree(F))
      return r
    end

    d = reduce(lcm, map(x->denominator(x, R), coefficients(defining_polynomial(F))))
    f = map_coefficients(x->numerator(Qt(d)*x, R), defining_polynomial(F), cached = false)
    if is_monic(f)
      r.trans = identity_matrix(Qt, degree(F))
      r.itrans = identity_matrix(Qt, degree(F))
      return r
    end

    # f is not monic: need Lenstra Order

    d = degree(F)
    M = zero_matrix(Qt, d, d)
    M[1, 1] = one(Qt)
    for i in 2:d
      for j in i:-1:1
        M[i, j] = coeff(f, d - (i - j))
      end
    end
    return GenOrd(r, M, one(Qt), check = check)
  end

  function GenOrd(O::GenOrd{S, T}, M::MatElem, d::RingElem; check::Bool = true) where {S, T}
    F = base_field(O.F)
    if base_ring(M) isa ZZPolyRing
      R = base_ring(Hecke.AbstractAlgebra.Generic.underlying_fraction_field(F))
      M = map_entries(x -> F(change_base_ring(QQ, x; parent = R)), M)
      M = divexact(M, F(change_base_ring(QQ, d; parent = R)))
    else
      M = map_entries(F, M)
      M = divexact(M, base_ring(M)(d))
    end
    Mi = inv(M)
    r = GenOrd(O.R, O.F, true)::GenOrd{S, T}

    r.is_equation_order = false
    if is_equation_order(O)
      r.trans = M
      r.itrans = Mi
    else
      r.trans = M*basis_matrix(O)
      r.itrans = basis_matrix_inverse(O)*Mi
    end
    check && map(representation_matrix, basis(r))
    return r
  end
end

mutable struct GenOrdElem{S, T} <: RingElem
  parent::GenOrd
  data::S
  coord::Vector{T}

  function GenOrdElem(O::GenOrd{S, T}, f::FieldElem, check::Bool = false) where {S, T}
    @assert parent(f) === O.F
    if check && !is_unit(integral_split(f, O)[2])
      error("element not in order")
    end
    r = new{typeof(f), elem_type(T)}()
    r.parent = O
    r.data = f
    return r
  end
end

################################################################################
#
#  Ideals
#
################################################################################

@attributes mutable struct GenOrdIdl{S, T}
  order::GenOrd{S, T}
  basis#::Vector{elem_type(GenOrd{S, T}}
  basis_matrix#dense_matrix_type(T)
  basis_mat_inv#dense_matrix_type(S)
  norm
  minimum
  is_prime::Int            # 0: don't know
                           # 1 known to be prime
                           # 2 known to be not prime
  is_zero::Int             # as above
  is_principal::Int        # as above

  gen_one::RingElem
  gen_two::GenOrdElem

  princ_gen::GenOrdElem
  prim_elem::GenOrdElem
  min_poly_prim_elem
  basis_in_prim
  phi

  splitting_type::Tuple{Int, Int}
                         #ordered as ramification index, inertia degree


  function GenOrdIdl(O::GenOrd{S, T}) where {S, T}
    r = new{S, T}()
    r.order = O
    r.is_prime = 0
    r.is_zero = 0
    r.is_principal = 0
    r.splitting_type = (0, 0)
    return r
  end

  function GenOrdIdl(O::GenOrd, M::MatElem)
    # basis_matrix must be an owned (non-view) n x n lower-left HNF matrix
    # ideal(O::GenOrd, M) ensures this
    n = degree(O)
    @assert nrows(M) == n
    @assert ncols(M) == n

    r = GenOrdIdl(O)
    r.basis_matrix = M
    return r
  end

  function GenOrdIdl(O::GenOrd, x::GenOrdElem)
    # create ideal of O generated by x
    @assert parent(x) === O
    r = GenOrdIdl(O)
    r.princ_gen = x
    r.is_principal = 1

    if iszero(x)
       r.is_zero = 1
    end

    r.norm = _make_canonical_in(O, norm(x))
    r.gen_one = r.norm
    r.gen_two = x
    return r
  end

  function GenOrdIdl(O::GenOrd, x::RingElem)
    return GenOrdIdl(O, O(x))
  end

  function GenOrdIdl(O::GenOrd, T::Vector{<:GenOrdElem})
    @assert all(x -> parent(x) === O, T)

    # TODO: One should do this block by block instead of the big matrix
    V = hnf(reduce(vcat, [representation_matrix(x) for x in T]), :lowerleft)
    return ideal(O, V; M_in_hnf = true)
  end

  function GenOrdIdl(O::GenOrd, p::RingElem, a::GenOrdElem)
    r = GenOrdIdl(O)
    r.gen_one = p
    r.gen_two = a
    return r
  end
end

@attributes mutable struct GenOrdFracIdl{S, T}
  order::GenOrd{S, T}
  num::GenOrdIdl{S, T}
  den::RingElem
  norm::RingElem
  basis_matrix#::FakeFracFldMat
  basis_mat_inv#::FakeFracFldMat

  function GenOrdFracIdl(O::GenOrd{S, T}) where {S, T}
    z = new{S, T}()
    z.order = O
    return z
  end

  function GenOrdFracIdl(a::GenOrdIdl{S, T}, b::RingElem) where {S, T}
    z = new{S, T}()
    O = order(a)
    z.order = O
    z.num = a
    z.den = _make_canonical_in(O, b)
    return z
  end

   function GenOrdFracIdl(a::GenOrdIdl{S, T}) where {S, T}
    z = new{S, T}()
    O = order(a)
    z.order = order(a)
    z.num = a
    z.den = O.R(1)
    return z
  end


  function GenOrdFracIdl(O::GenOrd{S, T}, a::MatElem) where {S, T}
    z = new{S, T}()
    z.order = O
    z.basis_matrix = a
    return z
  end
end
