################################################################################
#
#      NfOrd/NfOrdIdl.jl : Ideals of generic orders in number fields
#
# This file is part of hecke.
#
# Copyright (c) 2015, 2016: Claus Fieker, Tommy Hofmann
# All rights reserved.
#
# Redistribution and use in source and binary forms, with or without
# modification, are permitted provided that the following conditions are met:
# * Redistributions of source code must retain the above copyright notice, this
#   list of conditions and the following disclaimer.
#
# * Redistributions in binary form must reproduce the above copyright notice,
#   this list of conditions and the following disclaimer in the documentation
#   and/or other materials provided with the distribution.
#
# THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS"
# AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE
# IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE
# DISCLAIMED. IN NO EVENT SHALL THE COPYRIGHT HOLDER OR CONTRIBUTORS BE LIABLE
# FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL
# DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR
# SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER
# CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY,
# OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE
# OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
#
#
#  Copyright (C) 2015, 2016 Tommy Hofmann
#
################################################################################

export show, ideal

################################################################################
#
#  String I/O
#
################################################################################

function show(io::IO, a::NfOrdIdlSet)
  print(io, "Set of ideals of $(order(a))\n")
end

function show(io::IO, a::NfOrdIdl)
  print(io, "Ideal of (")
  print(io, order(a), ")\n")
  print(io, "with basis matrix\n")
  print(io, basis_mat(a))
end

################################################################################
#
#  Construction
#
################################################################################

doc"""
***
    ideal(O::NfOrd, a::fmpz) -> NfOrdIdl

> Returns the ideal of $\mathcal O$ which is generated by $a$.
"""
ideal(O::NfOrd, a::fmpz)  = NfOrdIdl(O, deepcopy(a))

doc"""
***
    ideal(O::NfOrd, a::Int) -> NfOrdIdl

> Returns the ideal of $\mathcal O$ which is generated by $a$.
"""
ideal(O::NfOrd, a::Int) = NfOrdIdl(O, a)

doc"""
***
    ideal(O::NfOrd, A::fmpz_mat) -> NfOrdIdl

> Assuming that $A$ is a $d \times d$ nonsingular integer matrix,
> this function returns the ideal $I$ given by $I = \bigoplus \mathbf Z \alpha_i$,
> where $(\alpha_1,\dotsc,\alpha_d) = (\omega_1,\dotsc,\omega_d) A^t$.
"""
ideal(O::NfOrd, a::fmpz_mat) = NfOrdIdl(O, deepcopy(a))

doc"""
***
    ideal(O::NfOrd, a::NfOrdElem) -> NfOrdIdl

> Returns the ideal of $\mathcal O$ which is generated by $a$.
"""
ideal(O::NfOrd, a::NfOrdElem) = NfOrdIdl(O, deepcopy(a))

