# include("AlgAss/AlgAssTypes.jl")
include("AlgAss/AbsAlgAss.jl")
include("AlgAss/AlgAss.jl")
include("AlgAss/AlgGrp.jl")
include("AlgAss/AlgMat.jl")
include("AlgAss/Elem.jl")
include("AlgAss/AlgMatElem.jl")
include("AlgAss/Map.jl")
include("AlgAss/Ideal.jl")
