include("GenOrd/Types.jl")
include("GenOrd/Auxiliary.jl")
include("GenOrd/FractionalIdeal.jl")
include("GenOrd/GenOrd.jl")
include("GenOrd/Ideal.jl")
include("GenOrd/Matrix.jl")
include("GenOrd/ResidueRing.jl")
