include("LinearAlgebra/FakeFmpqMat.jl")
include("LinearAlgebra/LatEnum.jl")
include("LinearAlgebra/Howell.jl")
include("LinearAlgebra/Solve.jl")
include("LinearAlgebra/SolveIntegral.jl")
include("LinearAlgebra/Semilinear.jl")
#include("LinearAlgebra/pseudo_matrix.jl")
