include("Map/Map.jl")
include("Map/ResidueRingPoly.jl")
include("Map/AbsNumFieldOrder{AbsSimpleNumField, AbsSimpleNumFieldElem}.jl")
include("Map/NumField.jl")
include("Map/NumberField.jl")
include("Map/GrpAb.jl")
include("Map/NfRel.jl")
include("Map/FqPolyRing.jl")
include("Map/automorphisms.jl")
include("Map/FiniteField.jl")
