add_verbose_scope(:NfMaxOrd)
add_assert_scope(:NfMaxOrd)

#set_verbose_level(:NfMaxOrd, 1)

include("NfMaximalOrder/NfMaximalOrder.jl")
include("NfMaximalOrder/Ideal.jl")
include("NfMaximalOrder/Zeta.jl")
include("NfMaximalOrder/FracIdeal.jl")
include("NfMaximalOrder/Clgp.jl")
include("NfMaximalOrder/GenNfOrdUnit.jl")
include("NfMaximalOrder/ResidueField.jl")
include("NfMaximalOrder/ResidueRing.jl")
include("NfMaximalOrder/FactorBaseBound.jl")
include("NfMaximalOrder/FacElem.jl")
include("NfMaximalOrder/LinearAlgebra.jl")
