include("NfRel/NfRel.jl")
include("NfRel/NfRel_ns.jl")
include("NfRel/NfRelOrd.jl")
include("NfRel/NfRelOrdElem.jl")
include("NfRel/NfRelOrdIdl.jl")
include("NfRel/NfRelOrdFracIdl.jl")
include("Map/NfRelOrd.jl")
