include("NfRel/NfRel.jl")
include("NfRel/NfRelNS.jl")
# include("NfRel/NfRelTypes.jl")
include("NfRel/NfRelOrd.jl")
include("NfRel/OrdElem.jl")
include("NfRel/Ideal.jl")
include("NfRel/FracIdeal.jl")
include("Map/NfRelOrd.jl")
include("NfRel/ResidueRing.jl")
include("NfRel/NEQ.jl")
