include("NfRel/NfRel.jl")
include("NfRel/NfRel_ns.jl")
# include("NfRel/NfRelTypes.jl")
include("NfRel/NfRelOrd.jl")
include("NfRel/OrdElem.jl")
include("NfRel/Ideal.jl")
include("NfRel/FracIdeal.jl")
include("Map/NfRelOrd.jl")
include("NfRel/ResidueRing.jl")
