include("ComplexEmbeddings/Generic.jl")
include("ComplexEmbeddings/QQ.jl")
include("ComplexEmbeddings/NfAbs.jl")
include("ComplexEmbeddings/NfAbsNS.jl")
include("ComplexEmbeddings/NfRel.jl")
include("ComplexEmbeddings/NfRelNS.jl")
